tock/tock

- src/chips/sam4l/chip.rs
- src/chips/sam4l/gpio.rs
- src/hil/gpio.rs
- src/platform/storm/gpio_dummy.rs
- src/platform/storm/lib.rs
Add support for GPIO interrupts in the SAM4L HAL.
The SAM4L groups pins into _ports_ (of 32 pins each). When an interrupt is recieved, the only way to tell which pin changed is to check the IFR register on the port (which has a bit for each pin). Therefore, we need to explicitly group pins in the code so we can map an offset in the port to an actual pin data structure. Fortunately, this has no real effect on code outside of the gpio module.
In contrast to my reading of the SAM4L user guide, it seems (from experience) that the a pin's output must be disabled to read the value of the pin. So, for now, a pin can only be in output or input mode, not both.
> GPIO interrupts in the SAM4L HAL.

- Makefile
- src/apps/app1/Makefile.mk
- src/apps/c_hello/Makefile.mk
- src/apps/c_sync/Makefile.mk
- src/apps/cpp_hello/Makefile.mk
- src/apps/libs/Makefile.mk
- src/arch/cortex-m4/Makefile.mk
- src/chips/sam4l/Makefile.mk
I ran into a problem where the build/apps/ folder wasn't being automatically created even though it was needed, so I added some dependencies to make the makefiles a little more robust.
This branch has a Travis CI error that doesn't seem to be my fault.
> Ensure build/ and build/apps/ exist when needed

- src/apps/c_blinky/Makefile.mk
- src/apps/c_blinky/loader.ld
- src/apps/c_blinky/main.c
This application alternately blinks LEDs #0 and #1 of the nRF51822
PCA10001 board.
Parts specific to this board (which may require refactoring into specific vs. common parts:
* Memory layout on the linker script (loader.ld)
* delay functions based on NOPs (implementation similar to the Nordic SDK)
* Pin assignments to LED_0 and LED_1
> Add sample "c_blinky" app

- .travis.yml
- src/arch/cortex-m0/Makefile.mk
- src/arch/cortex-m0/ctx_switch.S
- src/arch/cortex-m0/syscalls.S
- src/chips/nrf51822/Makefile.mk
- src/chips/nrf51822/crt1.c
- src/chips/nrf51822/gpio.rs
- src/chips/nrf51822/lib.rs
- src/chips/nrf51822/loader.ld
- src/chips/nrf51822/target.json
- src/platform/nrf_pca10001/Makefile.mk
- src/platform/nrf_pca10001/lib.rs
Add support for the PCA10001 board with the nRF51822 SoC. This initial support contains just the minimal support for the "blinky" app to work:
* Context switching to/from kernel
* GPIO output pins
* Programming using JLink Debugger
> Initial support for nRF51822

- extern/rust/Makefile.mk
I tried to run make on windows platform today, with some failures. This should fix it. Please test on other platforms, they should not be affected.
tar - force local, as colon is used for paths in windows
wget - ignore certificate
My output for nrf platform blinky:
```
make VERBOSE=1 platform=nrf_pca10001 CHIP=nrf51822 APPS=c_blinky
Building build/crt1.o
Need libcore to compile Tock: fetching source rustc-7dce32e65-src.tar.gz
SYSTEM_WGETRC = c:/progra~1/wget/etc/wgetrc
syswgetrc = C:\Programs\GnuWin32\wget/etc/wgetrc
Extracting rustc-7dce32e65-src.tar.gz
Building build/core-7dce32e65/libcore.rlib
Copying build/core-7dce32e65/libcore.rlib to build/libcore.rlib
Building build/libsupport.rlib
Building build/libcommon.rlib
Building build/libprocess.rlib …
```
> Rust makefile - wget and tar fix for windows related problems

- src/platform/storm/lib.rs
Proposed fix for issue #54. ESCL is assigned to PB01 (correct) instead of PB02 (incorrect).
> Fix issue #54 (ESCL assigned to incorrect pin)

- src/chips/sam4l/ast.rs
- src/drivers/timer.rs
- src/drivers/virtual_alarm.rs
- src/hil/alarm.rs
- src/platform/storm/lib.rs
Fixes major (and some minor) issues throughout the virtual timer stack. The high bits:
* The SAM4L AST capsule wasn't waiting on the busy bit to before reading the current timer value and the alarm registers. This resulted in alarms appearing to fire before the alarm that was set (because `now` was reading stale values)
* The `virtual_alarm` capsule wasn't properly accounting for enabled and disabled virtual alarms.
* The `TimerDriver` (virtual timer for processes) was not consistently translating from milliseconds (which is the unit the driver accepts) to native clock frequency (in the case of SAM4L's AST 16Khz), resulting in basically all virtual timers being fired almost every time.
> Timer overhaul

- src/drivers/isl29035.rs
- src/drivers/virtual_i2c.rs
We were just allowing enable/disable to go through unaccounted for on `I2CDevice` (virtual I2C devices) and `MuxI2C`. This manifested as a particularly nefarious bug where if the TMP and ISL drivers where operating simultaneously (e.g. in the `sensors` app), and the TMP happened to disable the I2C while the ISL was in the middle of a multi-transaction operationg (e.g. preparing and reading the sensor), the bus would get block forever.
> Properly account for enable/disable in virtual I2C

- src/arch/cortex-m0/ctx_switch.S
- src/arch/cortex-m4/ctx_switch.S
- src/chips/sam4l/chip.rs
- src/main/main.rs
- src/main/sched.rs
- src/process/process.rs
When a hardware interrupt comes in, switch immediately to the kernel instead of returning to user-space, prioritizing all kernel code over user-space.
* Generic ISR saves process state in the same way as `switch_to_user`, but only if coming from a process.
* The process scheduler breaks out of the process if `switch_to_user` returns but a syscall wasn't fired
Resolves: #63
> Prioritize IRQs over user-space processes

- src/arch/cortex-m4/ctx_switch.S
- src/chips/sam4l/lib.rs
- src/main/main.rs
- src/main/sched.rs
- src/platform/nrf_pca10001/lib.rs
- src/platform/nrf_pca10001/systick.rs
- src/platform/storm/lib.rs
- src/platform/storm/systick.rs
- src/process/process.rs
* Implements systick for the cortex-m4
* Limits each processes to 10ms at a time before yielding to other processes
> Timeslice processes using systick

- src/main/sched.rs
- src/platform/storm/systick.rs
There is no good reason that `set_timer` and `value` didn't agree on units, just makes things needlessly complicated.
Now, both treat the value (argument to `set_timer` and return value from `value()`) as microseconds. This also fixes issues with the dummy systick for the nrf51822
Tested by merging into one of the nrf51822 branches, result is here: https://github.com/alevy/tock/commit/655af45f72b56fa063524ac78ed6a9fd204932ed
> Use same units in systick's set_timer and value

- src/arch/cortex-m4/Makefile.mk
- src/arch/cortex-m4/ctx_switch.S
- src/arch/cortex-m4/lib.rs
- src/arch/cortex-m4/mpu.rs
- src/chips/sam4l/Makefile.mk
- src/chips/sam4l/chip.rs
- src/chips/sam4l/lib.rs
- src/main/sched.rs
- src/platform/nrf_pca10001/lib.rs
- src/platform/storm/lib.rs
- src/process/process.rs
- tools/elf2tbf/src/main.rs
We have a new crate for the cortex-m4, containing Rust code that's general to the cortex (i.e. not sam4l specific). This patch adds the MPU implementation for the m4 to that crate (the systick belongs there too, but that's for another PR).
This patch sets up an MPU with two regions:
* A region for the application code section, marked read and execute (not write).
* A region for the application memory marked read/write/execute.
The default region is disabled for unprivileged code, which means by default unprivileged code cannot access anything not explicitly enabled by another region.
TODO:
-  [x] Stub for NRF
> Use MPU to isolate applications

- src/drivers/console.rs
A subtle bug in the console driver resulted in losing all future console writes from all but the second app to write concurrently to the console.
> Don't loose app buffer in console when writing from multiple apps

- src/platform/nrf_pca10001/lib.rs
- src/platform/storm/lib.rs
- Changed `static_init!()` to take a size argument. This size argument should ideally be inferred, but for now we write it manually and do a compile-time verification that it is correct.
- Changed the type signature from `pub unsafe fn init<'a>() -> &'a mut Firestorm ` to `pub unsafe fn init() -> &'static mut Firestorm`, since the first is just a more convuluted way of writing the second.
> Changed the static_init macro to take a size argument

- src/main/sched.rs
- src/platform/nrf_pca10001/lib.rs
- src/platform/storm/lib.rs
Changes the platform structure name from Firestorm to Platform.
> Platform, not Firestorm

- .travis.yml
Updates travis configuration to pull proper version of arm-none-eabi on OS X
> Homebrew default arm-none-eabi is now 4.9

- src/main/main.rs
- src/process/process.rs
- tools/elf2tbf/src/main.rs
This removes a lot of hapzard offsetting from the process loader. Also clean up various part of the process loader.
> Move process image size to LoadInfo header

- src/drivers/nrf51822_serialization.rs
- src/drivers/spi.rs
- src/platform/storm/lib.rs
In general, drivers should use containers (Grants) to store app specific
state, and not depend on the number of processes allowed by the
platform.
The two specific examples that needed fixing were not virtualized
anyway, so we may as well just store a single app's state and pray for
the best (i.e. that only one app uses them) since two apps using them
was already problematic.
> Remove dependency on NUM_PROCS in driver

- src/common/src/utils.rs
- src/platform/nrf_pca10028/src/main.rs
- src/platform/storm/src/main.rs
Made the `static_init!` macro live in the `common` crate instead of in every platform. Changed its usage slightly and changed the platforms to match.
> Common static_init!

- src/chips/sam4l/src/chip.rs
Useful for using peripherals on the pinned out I2C bus of Firestorm.
> Assign a DMA channel to the second I2C bus

- src/chips/sam4l/src/spi.rs
- src/drivers/src/lib.rs
- src/drivers/src/spi.rs
- src/drivers/src/virtual_spi.rs
- src/hil/src/lib.rs
- src/hil/src/spi.rs
- src/platform/storm/src/main.rs
- src/platform/storm/src/spi_dummy.rs
- Try to get SPI to better parallel I2C and other parts of Tock.
- Add layer that incorporates the chip select line (much like I2CDevice).
- Remove the option<> on txbuffer (which is not optional).
- Fix issues with SPI+DMA.
> Normalize SPI and add virtual_spi.rs

- kernel/src/driver.rs
- kernel/src/process.rs
- kernel/src/sched.rs
- kernel/src/syscall.rs
- userland/examples/ble-serialization/serialization.c
- userland/examples/gpio_test/main.c
- userland/examples/rf233/rf233.c
- userland/examples/tmp006/main.c
- userland/libtock/crt1.c
- userland/libtock/firestorm.c
- userland/libtock/isl29035.c
- userland/libtock/tmp006.c
- userland/libtock/tock.c
- userland/libtock/tock.h
`wait` conflicts with libc's `wait`, which causes a naming conflict. It's also potentially confusing (if you type `man 2 wait` you get something, but it's not Tock's `wait`).
I don't think `yield` is overloaded in the C standard library. Alternatives, though:
* `sys_wait` (and we would change the other syscalls to `sys_`)
* `tock_wait`
* ... ideas?
/cc @brghena
> Rename `wait` to `yield`

- boards/nrf51dk/Makefile
- boards/nrf51dk/layout.ld
- boards/nrf51dk/nrf51.json
- boards/storm/Makefile
- boards/storm/layout.ld
- boards/storm/sam4l.json
- chips/nrf51/build.rs
- chips/nrf51/layout.ld
- chips/nrf51/nrf51.json
- chips/sam4l/Cargo.toml
- chips/sam4l/build.rs
- chips/sam4l/layout.ld
- chips/sam4l/sam4l.json
Relocating the linker script and target specs to the boards directory lets boards customize them. For example, a particular board (e.g. the Firestorm) may need to leave room for a bootloader before the vector table.
It also lets us get rid of the hacky dependency on the output directory name in the target specification.
> Move linker script and target spec to boards

- chips/sam4l/src/lib.rs
- chips/sam4l/src/pm.rs
So I basically went through what `sysclk_init` in the ASF does and copied it. Code is not pretty right now, but wanted to get this out there because after very first testing it seems to work.
What I can't figure out is why I have to set the multiplier to 1563 instead of 1464 (or 48000000 / 32768).
> Remove need for bootloader to init clocks

- kernel/src/common/take_cell.rs
Better mirrors the API of other Rust objects.
> Add `is_some()` to TakeCell

- boards/nrf51dk/Makefile
- boards/nrf51dk/apps/blink
- boards/nrf51dk/jtag/flash-full.jlink
- boards/nrf51dk/jtag/flash-kernel.jlink
- chips/nrf51/layout.ld
Allows programming over JLINK of the kernel + one app for the nrf51dk. The app must be located in `boards/nrf51dk/apps/APP_NAME`. As a starter, I've symlinked the blink example app into that folder. Now, from the nrf51dk folder you can run:
```
$ make program-full APP=blink
```
> Build rules to program kernel + app on nrf51dk

- chips/nrf51/src/uart.rs
Every time a byte is transmitted, it generates a TXDRDY event by setting this register to 1. This must be manually cleared before another byte can be sent. 
See sections 10.1.3 and 29.4 of the nRF51822 manual.
> Send multiple bytes by setting txdrdy to 0

- chips/sam4l/src/dma.rs
- chips/sam4l/src/i2c.rs
- chips/sam4l/src/spi.rs
- chips/sam4l/src/usart.rs
Change DMA xfer_done interface to return a DMAPeripheral enum to clients rather than a u32.
Making this pull request because it's unclear what the best method for changing a numerical register value into an enum in rust.
> Changed xfer_done DMA interface

- boards/nrf51dk/src/main.rs
- boards/storm/src/main.rs
- capsules/src/gpio.rs
- capsules/src/tmp006.rs
- capsules/src/virtual_spi.rs
- chips/nrf51/src/gpio.rs
- chips/sam4l/src/gpio.rs
- kernel/src/hil/gpio.rs
- kernel/src/hil/led.rs
Not much here except for comments. Highlights:
- Changed `enable` to `make` when setting up GPIO pins.
- Changed `GPIOPin` to just `Pin`. This better mirrors `Client` (which is not `GPIOClient`) and should be fine when using namespacing (i.e. `hil::gpio::Pin`).
- Document what `disable` is supposed to do.
> Start on changes to GPIO HIL interface.

- chips/nrf51/src/uart.rs
ptr::write_volatile and read_volatile no longer used in uart.rs; each register is now a VolatileCell.
> Changes NRF UART from ptrs to volatile cells

- chips/sam4l/src/dma.rs
- chips/sam4l/src/i2c.rs
- chips/sam4l/src/spi.rs
- chips/sam4l/src/usart.rs
- kernel/src/common/take_cell.rs
This is dependent on `map_or`.
Gets rid of need for `&mut Self` in `dma.xfer_done`.
> Update DMA in SPI/USART to be in TakeCell

- boards/storm/src/main.rs
- capsules/src/spi.rs
- capsules/src/virtual_spi.rs
- chips/sam4l/src/spi.rs
- kernel/src/hil/spi.rs
Makes an enum that gets passed to `set_chip_select()` so the drivers can use a GPIO pin or a hardware chip select line. 
I need help with virtual_spi.rs. In order to get types to work, I had to call `take()` on the chip select enum before passing it to the hardware. If I'm not mistaken, that will remove it and will effectively only work once. So if there is more than one SPI device, the CS line will not get properly updated.
I also have to make GPIO CS work with the sam4l spi peripheral.
> SPI: Support GPIO chip select as well as HW chip select

- boards/nrf51dk/apps/c_hello
- chips/nrf51/nrf51.json
- userland/Makefile
* Adds +strict-align to the nrf51 target specification so LLVM doesn't generate byte-aligned load/stores for the kernel
* Use thumbv6 libc.a for userland so we don't end up with apps that have incorrect instructions for Cortex-M0
* Fixup userland Makefile to link in arm intrinsics required to replace the instructions above.
> Compile Cortex-M0 apps and more better

- chips/sam4l/src/adc.rs
- chips/sam4l/src/ast.rs
- chips/sam4l/src/bpm.rs
- chips/sam4l/src/dma.rs
- chips/sam4l/src/nvic.rs
- chips/sam4l/src/pm.rs
- chips/sam4l/src/scif.rs
- No reason a register address could be negative.
- Also no need for them to be public.
> SAM4L: Make base addresses `usize`

- chips/sam4l/src/spi.rs
Also rename "regs" to "registers" to be inline with I2C.
> SAM4L: Update SPI to volatile cell

- .travis.yml
- boards/imix/Cargo.lock
- boards/imix/Cargo.toml
- boards/imix/Makefile
- boards/imix/Makefile-app
- boards/imix/connect.cfg
- boards/imix/debug.gdb
- boards/imix/layout.ld
- boards/imix/sam4l.json
- boards/imix/src/io.rs
- boards/imix/src/main.rs
- userland/tools/flash/imix.sh
Basic board definition including:
* Console, gpio and timer drivers
* Process loading (done the same as firestorm)
* Flashing the kernel with openocd
* Flashing apps with openocd (multiple apps supported)
@shaneleonard can you take a look at the pin configurations? I copied from Firestorm. What's different (if anything)? What needs to be added (e.g. for power domain control, sampling the RNG, etc)?
> Add Imix board definition

- boards/storm/src/main.rs
- capsules/src/adc.rs
- capsules/src/lib.rs
- chips/sam4l/src/adc.rs
- chips/sam4l/src/chip.rs
- kernel/src/hil/adc.rs
- userland/examples/adc/Makefile
- userland/examples/adc/main.c
- userland/libtock/adc.c
- userland/libtock/adc.h
All credit for this goes to @nealjack, I just cleaned up the branch for making a pull request.
Marked blocked to allow for more testing.
Also, the register list uses `#[cfg_attr(rustfmt, rustfmt_skip)]`. Doesn't that defeat the point? Or do we want to align all structs like that? Can we get `rustfmt` to do that?
Also, @nealjack feel free to take ownership of these commits. Git was doing the right thing all the way until I split it into two commits.
> Update SAM4L ADC and add ADC capsule

- capsules/src/fm25cl.rs
- capsules/src/lib.rs
1. Provides both an internal interface and a Driver interface.
2. I have userland code, but I don't think we really don't want to have .c/.h files for every FRAM chip. Ideally we would have a generic interface, that can be supported by any nonvolatile chip.
> Add FM25CL driver.

- boards/nrf51dk/src/main.rs
- boards/storm/src/main.rs
- capsules/src/led.rs
- capsules/src/lib.rs
- userland/examples/blink/main.c
- userland/examples/blink_sync/main.c
- userland/examples/c_gpio/main.c
- userland/examples/security_app/main.c
- userland/examples/spi_buf/main.c
- userland/examples/spi_byte/main.c
- userland/libtock/led.c
- userland/libtock/led.h
Also change pin assignments in boards to separate LED pins from other
GPIO pins. Then update apps to use the new pin mappings, cleaning along
the way. A nice benefit of this approach is that we don't have to have a
header file that maps "LED_0" to the correct gpio pin number. To use the
first LED, just call the `led_*()` functions with the number 0.
> Add LED capsule

- boards/imix/src/main.rs
Imix pin assignments differ slightly from the Firestorm pin assignments, so I've corrected them in the board initialization.
@shaneleonard would be good to get a second pair of eyes. The relevant modifications are in `boards/imix/src/main.rs` in the `set_pin_primary_functions` function.
> Correct Imix pin assignments

- boards/imix/src/main.rs
- boards/nrf51dk/apps/c_gpio
- boards/nrf51dk/src/main.rs
- capsules/src/button.rs
- capsules/src/lib.rs
- chips/nrf51/src/gpio.rs
- chips/sam4l/src/gpio.rs
- userland/examples/c_gpio/main.c
- userland/libtock/button.c
- userland/libtock/button.h
Adds a button driver, similar to the LED driver, to make applications
using buttons more portable.
* Fixes a bug in the SAM4L gpio setup.
* Add button driver to Imix
~~There are some issues with the NRF51dk buttons (the PIN_CNF doesn't seem to be sticking for some reason, and a PullUp is required, otherwise it works), so that's blocking me on porting to the NRF51dk~~
> Button driver

- chips/sam4l/src/chip.rs
Add USART0/1 and I2C0 for platforms that use those peripherals.
> SAM4L: Assign more DMA channels

- chips/sam4l/src/lib.rs
- chips/sam4l/src/wdt.rs
- kernel/src/hil/mod.rs
- kernel/src/hil/watchdog.rs
Add the driver for the SAM4L platform.
Also adds a very simple HIL interface.
> SAM4L: Add HW watchdog

- capsules/src/i2c_master_slave_driver.rs
- capsules/src/lib.rs
- userland/libtock/i2c_master_slave.c
- userland/libtock/i2c_master_slave.h
Provides a `Driver` interface for listening for and transmitting I2C messages.
> Add I2C Master/Slave Capsule

- boards/imix/src/io.rs
- boards/imix/src/main.rs
- boards/nrf51dk/src/main.rs
- boards/storm/src/io.rs
- boards/storm/src/main.rs
- capsules/src/console.rs
- capsules/src/nrf51822_serialization.rs
- chips/nrf51/src/uart.rs
- chips/sam4l/src/chip.rs
- chips/sam4l/src/usart.rs
- kernel/src/hil/uart.rs
- userland/examples/ble-serialization/serialization.c
- userland/libtock/nrf51_serialization.c
- userland/libtock/nrf51_serialization.h
UART updates
- Updates UART HIL to an asynchronous interface
- Updates USART implementation of UART to fit and to generally be better
- Updates Console and nrf-serialization to fit
- Updates `io.rs` with new UART interface
DMA updates
- DMA peripheral stuff will mostly disappear once PR #125 hits (intend to merge this after #125)
- Added all the possible DMA interrupts so no one would ever forget to do so again
`take_cell` updates
- added `map_or` function that had a good use as a common idiom in UART and SPI to reduce possible mistakes. Otherwise, implementation requires a `take()` and then remembering to `replace()` in the same code block
Missing Functionality
- `io.rs` currently requires some backdoor methods into the USART until we can figure out how to send static strings to the UART …
> UART HIL redesign with asynchronous calls

- boards/imix/src/main.rs
- boards/storm/src/main.rs
- chips/sam4l/src/i2c.rs
- chips/sam4l/src/lib.rs
- chips/sam4l/src/pm.rs
- chips/sam4l/src/spi.rs
- chips/sam4l/src/usart.rs
Because there are now multiple clock options, setting the clock has to be a platform specific option.
I do need help making a function that returns the current system clock frequency (for use in things like usart.rs). The way it's setup right now it needs unsafe. Is there a good way to do this that doesn't need unsafe? Should I go all the way to making `pm` a struct like the other modules?
> Add ability to use OSC0 as system clock

- chips/sam4l/src/spi.rs
Hey @alevy and @bradjc, 
I'm working on a fix for the SPI for the RF233 in terms of the 'race condition' bug I was getting from aborting the read after the write finish. 
Using a newer codebase ( than the one I originally forked off of ), which is this branch, further modifications to SPI have complicated things. 
I found an off-by-1 bug in the `ChipSelect` that inits the SPI (it forgot to account for Peripheral 3), such that a userland syscall to `specify_chip_select` would fail on peripheral 3. 
Given that I've fixed that in this pull req, I'm a bit lost on why my logic analyzer is saying that the MISO is always 0. Maybe you guys might have a clue...
> Sam4l Spi fix

- arch/cortex-m0/src/lib.rs
- arch/cortex-m4/src/lib.rs
- kernel/src/process.rs
_This PR requires pretty detailed review. Putting this up early to start to get feedback_
Previously, we were storing the process registers on the process stack
on an SVC or interrupt. However, that is a huge security hole since
we're trusting the integrity of the PSP register to the process, which
could point it anywhere it wanted.
Instead this stores the registers in a fixed location per process, which
is kept track of using supervisor mode's r0 register (on the kernel
stack while running a process is running)
> [Security] Store process registers in Process struct

- capsules/src/led.rs
- userland/examples/blink/main.c
- userland/libtock/led.c
- userland/libtock/led.h
Rather than just blink 1 LED, it now adapts to the number of LEDs on the platform. This is good not only because it looks cooler, but it's a step towards more portable apps.
It does raise a question about what should return this type of information (i.e. "how many LEDs?" or "is there a temperature sensor?"). Each driver somehow? Or something more directly provided by the kernel?
> Make blink app adapt to underlying platform

- Makefile
- tools/list_boards.sh
`make list` prints out the list of boards in Tock. This should help people understand what they can build Tock for.
I'd like to make this more descriptive, like:
```
Tock Boards:
storm  - Ardiuno form factor dev board  - https://storm.rocks
imix  - ...
...
```
but for now this will do.
> Add `make list`

- boards/nrf51dk/src/main.rs
- chips/nrf51/src/lib.rs
- chips/nrf51/src/pinmux.rs
- chips/nrf51/src/uart.rs
The NRF51 does not have a separate pinmux controller like the SAM4L (where it is integrated into the GPIO controller). Instead, each controller decides which pins to use, and it is possible for two controllers to choose the same pins. Behavior is undefined in this case, but at best, this would leak information between controller drivers.
This change exposes an opaque type, `Pinmux` in the nrf51 crate that simply wraps a `u32` such that only trusted code can construct it.
> Use opaque pinmux type for configuring nrf51 pins

- capsules/src/button.rs
- userland/examples/buttons/main.c
- userland/libtock/button.c
- userland/libtock/button.h
Like @bradjc's recent LED driver change, this adds a count system call to the buttons driver so an app can query how many buttons there are on a particular platform.
> Add count system call to buttons driver

- chips/sam4l/src/adc.rs
- userland/libtock/adc.c
For some reason the ADC interrupt handler is firing twice for every adc
sample. I checked the status register, and the result is 0x51000001,
where the top 3 1s indicated various things are enabled, and the LSB is
one indicating that the conversion is finished. The status register on
the second interrupt is just 0x51000000.
What we really care about is not calling the callback twice, and this
ensures we only call the callback on the correct interrupt.
Also, `result.fired` needs to be cleared in the userland ADC library.
> SAM4L ADC: Fix multiple interrupt issue

- kernel/src/process.rs
Before this commit, 8KB processes sizes were assumed when setting the
MPU rules for a process. This commit fixes this to compute the MPU size
based on the length of `Process#memory.len()`.
Solves #191
> Allow non-fixed process size when setting up MPU

- boards/hail/src/main.rs
- boards/imix/src/main.rs
- capsules/src/fxos8700_cq.rs
Correctly parses the accelerometer driver's output as signed, 16-bit
0.244mg and converts to 1mg signed 16-bit units.
Fixes #208
> Fix FXO accelerometer driver resolution and units

- userland/examples/accel-leds/Makefile
- userland/examples/accel-leds/README.md
- userland/examples/accel-leds/main.c
- userland/libtock/FXOS8700CQ.c
- userland/libtock/FXOS8700CQ.h
This is a pretty good test app for the accelerometer because as you hold the board in different orientations, different LEDs come on.
It also adds a `sync` function for getting acceleration data.
> Add Accelerometer to LEDs App

- .travis.yml
This removes the need to rebuild rustfmt on each test, saving 6 minutes of Travis time.
> travis: Enable caching cargo packages

- .travis.yml
This should build linux all the time (like before) but save the slower mac build for only
when a commit gets to master so we can keep an eye on the mac build, without having to wait for it on every commit.
> travis: Only build mac on master

- capsules/src/console.rs
- userland/examples/tests/printf_long/Makefile
- userland/examples/tests/printf_long/main.c
This adds support for keeping track of how much of an AppSlice the console has printed, and continuing to print after the uart callback.
Should fix #57
> Console: Print buffers longer than 64 bytes

- kernel/src/container.rs
- kernel/src/process.rs
The specific bug was that the iterator for a container was checking for
null-ness of the pointer to the container rather than the container
itself. As a result, if a container was empty, rather than skipping over
it, it would just dereference 0x0 a cast it to the container type. Bad
news, but this code path hadn't really been tested.
The fix is a bit more expansive. Instead of returning a
pointer-to-a-pointer from `container_for`, we just return a single
pointer so this kind of confusion is harder to make.
> Fix bug in container/grant iterator

- chips/sam4l/src/chip.rs
- chips/sam4l/src/lib.rs
- chips/sam4l/src/trng.rs
- kernel/src/hil/mod.rs
- kernel/src/hil/rng.rs
The RNG HIL uses a generator pattern to yield a stream of random numbers to the client as they become available.
The client requests randomness by calling `RNG#get`. When randomness is available, the client's `randomness_available` method is called along with an iterator over a stream of random `u32`s. When done iteraterating, the client can request more through the return value (which is either `More`, or `Done`).
This pattern balances the fact that generating new randomness might take arbitrarily long (e.g. especially in the case of a virtualized RNG) and that randomness might be available in batches, with the observation that often applications will need more than a single `u32` of randomness (e.g. to fill an 128-bit initialization vector).
> Random Number Generator HIL & Implementation for SAM4L

- capsules/src/fxos8700_cq.rs
- userland/examples/find_north/Makefile
- userland/examples/find_north/README.md
- userland/examples/find_north/main.c
- userland/libtock/FXOS8700CQ.c
- userland/libtock/FXOS8700CQ.h
- Add all FXO registers
- Only added simple one-shot read, much like the current acceleration interface.
- Added a test app. The app is calibrated for Hail. I'm not sure how to tell applications which way the x, y, and z directions are.
> Add magnetometer read to FXOS8700CQ

- userland/Makefile
- userland/examples/accel-leds/Makefile
- userland/examples/adc/Makefile
- userland/examples/ble-env-sense/Makefile
- userland/examples/blink/Makefile
- userland/examples/blink_sync/Makefile
- userland/examples/build_all.sh
- userland/examples/buttons/Makefile
- userland/examples/c_hello/Makefile
- userland/examples/cxx_hello/Makefile
- userland/examples/rf233/Makefile
- userland/examples/rot13_client/Makefile
- userland/examples/rot13_service/Makefile
- userland/examples/security_app/Makefile
- userland/examples/sensors/Makefile
- userland/examples/spi_buf/Makefile
- userland/examples/spi_byte/Makefile
- userland/examples/tests/FXOS8700CQ/Makefile
- userland/examples/tests/gpio/Makefile
- userland/examples/tests/hail/Makefile
- userland/examples/tests/lps25hb/Makefile
- userland/examples/tests/printf_long/Makefile
- userland/examples/tests/si7021/Makefile
- userland/examples/tests/tmp006/Makefile
- userland/examples/tests/tsl2561/Makefile
- userland/examples/tutorials/02_button_print/Makefile
- userland/examples/tutorials/03_ble_scan/Makefile
- userland/libnrfserialization/Makefile.app
- userland/libtock/Makefile
A lot of the makefile was just being copy and pasted between apps and didn't really need to be.
This also makes it easier to add new apps in different folders as only one line has to change rather than two.
> Streamline userland apps makefiles

- capsules/src/virtual_alarm.rs
In certain cases where there are multiple virtual timers and events line up just right, certain timers could be missed. To handle wrapping concerns, timers are compared against a "previous" timestamp, however
this "previous" value can change while the virtual timers are being checked. This can cause a valid timer's "when" time to be less than the new previous value and the timer won't fire.
If I'm not mistaken, this issue happens when three things are true:
1. Two virtual timers are set to fire in the same 100 tic window.
2. One of the timers is from timer.rs.
3. The timer.rs timer is earlier in the array of multiplexed timers.
Because timer.rs will reschedule a timer if it fires too early (becauseof the window) it calls `set_timer()` and `self.mux.prev` is updated to a new time.
Checking …
> Fix issue with missed timers in virtual_alarm.rs

- userland/Makefile
Errors if someone tries to use `~` instead of `$(HOME)`.
Fixes #242 
Seemingly confirmation that using ~ is just bad: https://github.com/sudar/Arduino-Makefile/issues/320
> userland: Check for ~ in TOCK_USERLAND_BASE_DIR

- kernel/src/returncode.rs
New:
```
ENOSUPPORT, // Operation or command is unsupported
ENODEVICE, // Device does not exist
```
Thoughts? I was looking for a way for a driver to say it doesn't support particular command. While I was there, it might be nice to signal that a device does not exist on a platform.
> kernel: Add new ReturnCode values

- kernel/src/callback.rs
- kernel/src/sched.rs
Rust's NonZero "function" is really just a compiler hint that the
value enclosed by it is guarenteed not to be zero. Critically, NonZero
doesn't check this, it trusts that the caller validated this in advance
(which is why it's an unsafe fn). We were violating this assumption.
My first instinct was to just rip out the NonZero, because it wasn't
really buying us much - this is just a pointer that rust is holding
onto. However, removing it caused every App struct that holds a
Callback to grow by 8 bytes, even still if you change the type of
`fn_ptr` to usize instead of a function (pointer), so clearly Rust's
optimizer is doing something magical and it's worth keeping around.
> Catch and reject null callback

- capsules/src/adc.rs
- capsules/src/button.rs
- capsules/src/console.rs
- capsules/src/fm25cl.rs
- capsules/src/fxos8700_cq.rs
- capsules/src/gpio.rs
- capsules/src/i2c_master_slave_driver.rs
- capsules/src/isl29035.rs
- capsules/src/led.rs
- capsules/src/lps25hb.rs
- capsules/src/nrf51822_serialization.rs
- capsules/src/rng.rs
- capsules/src/si7021.rs
- capsules/src/spi.rs
- capsules/src/timer.rs
- capsules/src/tmp006.rs
- capsules/src/tsl2561.rs
- kernel/src/driver.rs
- kernel/src/ipc.rs
- kernel/src/process.rs
- kernel/src/returncode.rs
- kernel/src/sched.rs
The driver trait now enforces sanctioned return codes throughout the kernel. Drivers can return any positive (non-error) value using `ReturnCode::SuccessWithValue`
I believe that all of the integer return codes were changed into the appropriate return code, but driver authors should double-check
> Use ReturnCode throughout kernel

- capsules/src/console.rs
The console callback is supposed to return the number of bytes that it
wrote, however, it was previously exposing the internal fragmentation
and returning that number of bytes written in the last uart transaction,
rather than the whole syscall.
> console: return actual number of bytes written

- capsules/src/console.rs
We were essentially doing the same thing in three places. That meant
that #260 only fixed the problem in 1 of 3 cases. This consolidates
the send logic into a shared helper function and makes more clear
when/how we're setting things up or continuing active transactions.
> console: consolidate send logic

- kernel/src/callback.rs
- kernel/src/hil/adc.rs
- kernel/src/hil/flash.rs
- kernel/src/hil/gpio.rs
- kernel/src/hil/i2c.rs
- kernel/src/hil/rng.rs
- kernel/src/hil/spi.rs
- kernel/src/hil/time.rs
- kernel/src/hil/uart.rs
- kernel/src/mem.rs
- kernel/src/platform/mpu.rs
- kernel/src/process.rs
I keep adding these ad-hoc. From a casual grep of pub.struct and
pub.enum, this should hopefully skip future annoying compile hangups.
From my understanding, debug traits cost nothing to derive, as their
implementations will automatically be dropped if nothing prints them.
It's probably a worthwhile question about what structures should have
Debug defined (should everything?), but that's for another day. For today,
just the trivial ones en masse.
> derive Debug trait for trivial kernel structures

- capsules/src/adc.rs
- capsules/src/button.rs
- capsules/src/console.rs
- capsules/src/fm25cl.rs
- capsules/src/fxos8700_cq.rs
- capsules/src/gpio.rs
- capsules/src/i2c_master_slave_driver.rs
- capsules/src/isl29035.rs
- capsules/src/led.rs
- capsules/src/lps25hb.rs
- capsules/src/nrf51822_serialization.rs
- capsules/src/rng.rs
- capsules/src/si7021.rs
- capsules/src/spi.rs
- capsules/src/timer.rs
- capsules/src/tmp006.rs
- capsules/src/tsl2561.rs
- kernel/src/lib.rs
@brghena points out that if ReturnCode is a public interface, its
import shouldn't be dependent on the internal module structure of
the kernel crate, and kernel should export it for other crates' use
If this goes through before #261 (likely), I promise to make the
requisite change there for you Phil :)
> export ReturnCode from returncode module

- .travis.yml
- Makefile.common
- arch/cortex-m4/src/scb.rs
- boards/hail/Cargo.lock
- boards/hail/src/io.rs
- boards/hail/src/main.rs
- boards/imix/Cargo.lock
- boards/imix/Cargo.toml
- boards/imix/build.rs
- boards/imix/src/io.rs
- boards/imix/src/main.rs
- boards/imix/src/spi_dummy.rs
- boards/nrf51dk/Cargo.lock
- boards/nrf51dk/src/main.rs
- boards/storm/Cargo.lock
- boards/storm/src/io.rs
- boards/storm/src/main.rs
- chips/sam4l/src/bpm.rs
- chips/sam4l/src/chip.rs
- chips/sam4l/src/dma.rs
- chips/sam4l/src/flashcalw.rs
- chips/sam4l/src/lib.rs
- doc/Getting_Started.md
- kernel/src/hil/spi.rs
- userland/tools/elf2tbf/Cargo.lock
- vagrant/Vagrantfile
This was pretty smooth and painless, mostly fixing up global variable
names to be all caps b/c that's caught now and a few structures got
smaller (whoo!)
One gotcha, the `#[lang=panic_fmt]` now requires you to also add a
`#[no_mangle]` directive, otherwise the symbol will be dropped and
you'll get an undefined reference to `rust_begin_unwind` (which is
what our `panic_fmt` function gets silently renamed to courtesy of
the magic of `#[lang=panic_fmt]`).
More info at https://github.com/rust-lang/rust/issues/38281
An unresolved mystery, imix currently gives this warning:
warning: function panic_fmt is marked #[no_mangle], but not exported,
#[warn(private_no_mangle_fns)] on by default
--> src/io.rs:40:1
|
40 | pub unsafe extern "C" fn panic_fmt(args: Arguments, file: &'static str, line: u32) …
> update to nightly-2017-01-25

- userland/Makefile
- userland/libtock/crt1.c
This was inspired by wanting this for kernel, but was way easier to
figure out how to do in userland first, and certainly doesn't hurt.
Unfortunately, I don't think we can do this for the kernel yet, from #rustc:
> userland: check stack size during compile

- boards/hail/src/io.rs
- boards/hail/src/main.rs
- boards/imix/src/io.rs
- boards/imix/src/main.rs
- boards/nrf51dk/src/main.rs
- boards/storm/src/io.rs
- boards/storm/src/main.rs
- capsules/src/lib.rs
- kernel/src/callback.rs
- kernel/src/container.rs
- kernel/src/debug.rs
- kernel/src/lib.rs
- kernel/src/process.rs
This adds support to use `debug!` in the kernel to print debugging messages. It requires platforms to wire the kernel to a console during platform init, and `panic!`s the debug message if it is used without it.
The kernel will act as a client app of the console, interfacing through the syscall interface. The debug structure within the kernel keeps a circular buffer that `debug!` writes into, slices of which are passed to the console, allowing debug printing to proceed asynchronously without blocking the kernel.
> Kernel debug support

- capsules/src/lib.rs
- capsules/src/sdcard.rs
- doc/Syscalls.md
- kernel/src/mem.rs
- kernel/src/returncode.rs
- userland/examples/sdcard/Makefile
- userland/examples/sdcard/main.c
- userland/libtock/sdcard.c
- userland/libtock/sdcard.h
- userland/libtock/tock.h
Implementation of a raw SD card interface for Tock. This code has been tested on the [Signpost Control Module](https://github.com/lab11/signpost/tree/master/hardware/controller/rev_b), [Storage Master platform](https://github.com/lab11/signpost/tree/master/software/kernel/boards/storage_master) on multiple 8 GB and 4 GB SDHC cards. The code should also be compatible with older, smaller SD cards, but has not been explicitly tested on them (I don't have any).
These commits should probably be squashed when merging.
`capsules/src/sdcard.rs`:
* `SDCard` for interacting with SD cards on a block level
* `SDCardDriver` implements syscalls for the `SDCard` interface
`userland/libtock/sdcard.c` and `userland/libtock/sdcard.h`:
* Functions for interacting with an SD card including checking if it is …
> SD Card driver

- doc/reference/trd-radio.md
Having documentation lead code is good. Writing the TRD made me realize that the 15.4 HIL needs a few small changes. In particular: initialization should not be part of the HIL (it is implementation specific, relates to bus vs. SoC), send_done needs an ack bool, and there need to be separate busy and started calls.
> TRD: 802.15.4 Radio HIL

- boards/hail/src/main.rs
- boards/imix/src/main.rs
- boards/storm/src/main.rs
- capsules/src/adc.rs
__WORK IN PROGRESS STILL__
This adds system call virtualization to the ADC driver so multiple applications can use the ADC concurrently. Initial tests seem to imply that it's working, but not totally as expected.
The goal is to provide the same sample to multiple apps if they both subscribed to the same channel. In practice what seems to be happening when programming the example ADC app twice, we get something like:
```bash
App1: [Tock] ADC Test
App2: [Tock] ADC Test
App1: ADC Reading: 2385 mV (raw: 0x0b90)
App1: ADC Reading: 2007 mV (raw: 0x09bb)
App2: ADC Reading: 2007 mV (raw: 0x09bb)
App1: ADC Reading: 1859 mV (raw: 0x0903)
App2: ADC Reading: 1627 mV (raw: 0x07e4)
App1: ADC Reading: 1855 mV (raw: 0x08ff)
App2: ADC Reading: 1692 mV (raw: 0x0834)
App1: ADC Reading: 1765 mV (raw: 0x088f) …
```
> Add syscall virtualization to ADC capsule

- doc/reference/trd103-gpio.md
This is the first stab at summarizing the GPIO HIL traits in TRD format.
Rendered: https://github.com/alevy/tock/blob/doc/trd103-gpio/doc/reference/trd103-gpio.md
> Write first draft of TRD103-gpio

- capsules/src/timer.rs
When application timers are set to fire very close to one another, it's possible for one of the later one to be passed over until another timer fires because by the time a new timer is set, `timer.now()` has just passed over it.
This resolves this issue by quantizing all application timer start times to the nearest one millisecond (which is closer to the behavior of a raw hardware timer operating at 1kHz anyway). This way application timers will always fire at exactly 1 millisecond interval, so timers that were otherwise close, will now be identical.
> Quantize application timers to 1 millisecond

- boards/hail/src/main.rs
- boards/imix/src/main.rs
- boards/nrf51dk/src/main.rs
- boards/storm/src/main.rs
- capsules/src/led.rs
This is necessary for boards that have a mixture of ActiveHigh and ActiveLow LEDs such as occurs on the Signpost platform.
In the end this is a pretty simple change. I'm hoping to have this merged today so that we can use it in signpost.
> Upgrade LED capsule to allow individualized modes

- arch/cortex-m4/src/lib.rs
- arch/cortex-m4/src/mpu.rs
- kernel/src/process.rs
- userland/examples/tests/mpu_walk_region/Makefile
- userland/examples/tests/mpu_walk_region/main.c
Debugging the MPU more revealed a Goldilocks situation: an off-by-one too large
and and off-by-one too small setting up MPU regions. Now we’re just right.
This explains two different issues we’ve been seeing:
- From #289: Applications could write the region of memory directly below them
- From @cxbrooks's exploration into very large apps that were seeing odd faults
First, an exploration of how the code was currently running:
Printing the MPU configuration:
TOCK_DEBUG(313): num 0 start_addr 0x20006000 len 14 base 0x20006010 attr_and_size 0x300001d
In the case the goals is to allow the range 0x20006000-0x20008000
Decomposing the registers:
1. region_base_address is set to 0x20006010
```
0010 0000 0000 0000 0110 0000 0001 0000
|                     |          | |...-> region 0
| …
```
> Fix MPU region sizes

- kernel/src/lib.rs
- kernel/src/process.rs
- userland/examples/tests/mpu_stack_growth/Makefile
- userland/examples/tests/mpu_stack_growth/main.c
- userland/libtock/crt1.c
- userland/userland_layout.ld
~~**Not Ready: Compile tested only**~~
Move application stack to the bottom of SRAM so that a stack overflow triggers an MPU fault rather than overwriting the data/got/bss segments
> Move application stack to bottom of SRAM

- userland/libtock/adc.h
- userland/libtock/button.h
- userland/libtock/console.h
- userland/libtock/firestorm.h
- userland/libtock/gpio.h
- userland/libtock/i2c_master_slave.h
- userland/libtock/ipc.h
- userland/libtock/isl29035.h
- userland/libtock/led.h
- userland/libtock/nrf51_serialization.h
- userland/libtock/radio.h
- userland/libtock/rng.h
- userland/libtock/sdcard.h
- userland/libtock/spi.h
- userland/libtock/timer.h
- userland/libtock/tmp006.h
- userland/libtock/tock.h
We were close to a consensus on most of this, but now everything
follows the same format:
`#pragma once` directive
[newline]
System headers in <>'s
[newline]
Tock headers in ""'s
[newline]
C++ guard
[newline]
#define's
[newline]
function prototypes
[newline]
C++ guard
The only real changes / decisions:
- `#pragma once` instead of include guards. We were about 50/50.
I think the pragma looks cleaner and is easier, so I went that way.
- C++ open guard above defines. We were about 75/25 this way already.
I think this is easier to parse as it groups the things this header
is defining together instead of putting this random build artifact
in the middle
- Add missing C++ guards. Only a few files had forgotten them. I don't
think any files were #define only, but even if they were, I'd be …
> be consistent with how we format headers

- kernel/src/common/math.rs
- kernel/src/process.rs
closest_power_of_two and the math for log_base_two are generally useful
functions that should be available in the math library for Tock
The motivation for this was that the upgraded ADC driver is going to need
these functions.
> Shared library for math functions

- doc/reference/trd1-trds.md
Here are the style issues addressed:
3. TRD Structure
- Adopt the ordering of elements as necessary for markdown:
title, header, body.
- Cite the "authoritative" description of markdown syntax:
https://daringfireball.net/projects/markdown/
3.1 Header
- Change header field "Author" to "Authors"
7. Author's Address
- Instead of non-standard triple-tics to format the address
information (which means rendering it may require github), it's just
as easy to use a markdown "code block", which is a paragraph with
every line indented by at least 4 spaces or 1 tab.
(See: https://daringfireball.net/projects/markdown/syntax#block)
8. Citations
- Use HTML anchors
> trd1: fix typos, try to address style issues

- doc/reference/trd-radio.md
- doc/reference/trd1-trds.md
- doc/reference/trd102-adc.md
- doc/reference/trd103-gpio.md
The section header formatting for TRDs was broken when rendered on github.com, but not when using [grip]() or other Markdown viewers. The crucial difference is that having the ```.``` means the [setext heading](https://github.github.com/gfm/#setext-heading) is rendered as an [empty list item](https://github.github.com/gfm/#setext-heading) as per the [GitHub Flavored Markdown spec](https://github.github.com/gfm/) and shown below:
So the ```6. Acknowledgements``` is rendered as plaintext, and the line below that is rendered as a divider.
I went through the ```doc/references``` folder and removed `.`'s, made the header sizes uniform, and cleaned up other Markdown around authors' addresses.
> Fix GFM quirks with setext headings and empty listed items

- Makefile.common
- doc/Getting_Started.md
- vagrant/Vagrantfile
`rustup` looks at the `RUSTUP_TOOLCHAIN` variable first to figure out
which toolchain to use (e.g. `nightly-2017-01-25`). Using this
environment variable avoids requiring developers building the kernel to
configure toolchain themselves.
Solves #321
> Use environment variable for force rustup toolchain version

- boards/hail/src/main.rs
Allocate all remaining memory for apps.
Allow 4 apps rather than a piddly 2.
> hail: Use all memory for apps.

- chips/nrf51/src/rtc.rs
`handle_interrupt` isn't actually clearing the interrupt, just prevent
the controller from delivering more interrupts to the PPI.
Address part of #320
> NRF51: Fix bug in RTC interrupt handling

- doc/Userland.md
- userland/examples/tests/mpu_stack_growth/main.c
- userland/examples/tests/mpu_walk_region/main.c
- userland/libtock/crt1.c
Closes #338.
This mostly implements the discussion from the issue thread, it:
- marks our `_start` in crt1 as weak
- overrides `_start` in tests where access memory regions is nice
- I view this as somewhat niche and a non-binding interface for now
- defines that standard main prototype as `int main(void)`
In the original issue thread, we'd suggested a prototype of `void main(void)`,
as Tock currently ignores the return value of processes. Unfortuntely, `-Wall`
turns on `-Wmain` by default, which results in
main.c:6:6: warning: return type of 'main' is not 'int' [-Wmain]
void main(void) {
^~~~
while we could explicitly turn this off (`-Wno-main`), my current feeling is
that writing `int main` is pretty stock for C, and having a return value from a
process may be useful someday (i.e. …
> be consistent about our defintion of `main`

- .travis.yml
- tools/toc.sh
When editing markdown files with tables of contents, it is very easy to change a heading but forget to re-generate the TOC. This adds support to travis to check to see if any TOC need updating.
This should also fail in Travis for exactly the reason why this PR exists.
> travis: check markdown files for TOC

- userland/TockLibrary.mk
- userland/libnrfserialization/Makefile
- userland/libtock/Makefile
This was motivated by looking at pulling signpost up to latest tock, and realizing that I'd have to basically copy over the Makefile from libtock and duplicate it, which itself was already duplicating stuff in TockLibrary.mk...
Now all libraries use one set of Make rules and it should be very lightweight to add new libraries into the build
> Dont special case libtock

- .travis.yml
- tools/toc.sh
* Fixes `rustfmt` version (superseded by #347, but makes the build pass for this PR at least)
* Moves `markdown-toc` checks until the end of the build process because somehow it seems to screw with Travis in some unreplicable way.
> Fix travis build failures

- chips/sam4l/src/i2c.rs
p727, sec 27.9.4 - ACKLAST is 25th bit not 24th
Nothing was actually using this (yet), but happened to notice
> sam4l: fix i2c ACKLAST bit

- userland/examples/tests/crash_dummy/Makefile
- userland/examples/tests/crash_dummy/README.md
- userland/examples/tests/crash_dummy/main.c
This app simply uses a press of the first button to trigger an app fault. This can be used for debugging to force the app state printouts.
> userland: add crash dummy app

- boards/Makefile.common
- boards/hail/src/io.rs
- boards/imix/src/io.rs
- boards/nrf51dk/src/io.rs
- chips/sam4l/src/lib.rs
This one is pretty experimental. I'm looking for opinions on whether this is the "best" way to do this.
The goal is to hopefully make it easier for us to test reported bugs by knowing what version of the kernel they occurred on
Currently the `TOCK_KERNEL_VERSION` is set to the `git describe` result, usually some combination of a tag and commit hash. https://git-scm.com/docs/git-describe#_examples
> Print the `TOCK_KERNEL_VERSION` on faults

- boards/hail/src/main.rs
- boards/imix/src/main.rs
- capsules/src/fxos8700_cq.rs
This addresses #226 and actually puts the accelerometer into standby mode. This makes it take longer to wakeup, so we need a timer to wait for the sample to be valid.
> fxos8700cq: put accelerometer into standby mode

- boards/hail/src/main.rs
- boards/imix/src/main.rs
- capsules/src/fxos8700_cq.rs
Rather than use a timer, prepare the accelerometer interrupt 1 and wait for it to fire when data is ready.
> fxos8700cq: Use data ready interrupt

- boards/hail/sam4l.json
- boards/imix/sam4l.json
- boards/nrf51dk/nrf51.json
`arm-none-eabi` doesn't have a redzone (ARM docs here, but dense:
http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.subset.swdev.abi/index.html)
`arm-windows-eabi` deos have an 8-byte redzone, and helpfully succinctly
clarifies that the standard ARM EABI doesn't have one:
https://msdn.microsoft.com/en-us/library/dn736986.aspx
This is a step towards unifying our target and the built-in Rust target
(with the goal of eliminating ours)
> Remove unused `disable-redzone` option

- arch/cortex-m4/src/mpu.rs
- kernel/src/common/math.rs
- kernel/src/mem.rs
- kernel/src/platform/mpu.rs
- kernel/src/process.rs
If the text segment of a process is not aligned to its size, use a larger region size that overlaps the  process region, and use the subregion field to activate only the text segment subregions.
In addition, fixes an off-by-one MPU region size issue, where the MPU's SIZE field is actually meant to be `Math.log2(region_length) - 1` (see section 4.5.5 of the Cortex-M4 User Guide). To codify this, the PR introduces a `PowerOfTwo` wrapper type and moves the logic of encoding the field to the MPU implementation.
Related to #297
> Enable MPU subregions for text segment when needed

- capsules/src/lib.rs
- capsules/src/ltc294x.rs
- doc/Syscalls.md
- userland/libtock/ltc294x.c
- userland/libtock/ltc294x.h
The LTC294X is a line of coulomb counters we use on signpost.
The 2491/2/3 have slightly different register sets and the capsule tries to do the right thing based on which is on the board. The capsule defaults to the ltc2941, and lets the actual chip be set at runtime because it may not be known when the kernel is compiled (as is the case for signpost).
> Add LTC294X Driver

- arch/cortex-m4/src/mpu.rs
- kernel/src/platform/mpu.rs
- kernel/src/process.rs
E.g. for text sections, data sections, grants and ipc regions.
Unfortunately, this currently makes the MPU hil a bit more Cortex-M MPU
specific... working on it.
This is somewhat in progress, but I think it might be worth merging meanwhile.
At this point, it make sense to makes the `Region` type to an associated of the `MPU` trait so it can be implementation specific and cache `Regions` between calls so the calculation is required each time (should drastically reduce the context switch time). However, both of these introduce to typing issues that call for some non-trivial refactoring of the kernel crate, and I'm still experimenting with.
Fixes #382
> Generalize MPU subregions and use where possible

- capsules/src/virtual_alarm.rs
- chips/nrf51/src/rtc.rs
- chips/nrf51/src/timer.rs
- chips/sam4l/src/ast.rs
- doc/reference/trd-time.md
- kernel/src/hil/time.rs
A first draft of the Time HIL TRD.
Going through writing the TRD, I think it makes sense to move `Frequency` to be part of the `Time` trait rather than `Alarm`. I included those changes here as well, although can do a separate PR if that's preferable. Since these changes are all at the type level, there should be no impact on runtime behavior.
> TRD104-time and related changes to Time HILs

- userland/examples/nrf51_temp_sensor/temperature.c
- userland/examples/nrf51_temp_sensor/temperature.h
- userland/examples/rf233/rf233.c
- userland/examples/sensors/main.c
- userland/examples/tests/crash_dummy/main.c
- userland/examples/tests/gpio/main.c
- userland/examples/tests/hail/main.c
- userland/examples/tests/tmp006/main.c
- userland/examples/tutorials/03_ble_scan/main.c
There are still some warnings in `examples/rf233` that I'm not sure how to fix (including two unimplemented functions).
> Clean up many userland compile warnings

- userland/AppMakefile.mk
- userland/TockLibrary.mk
This streamlines the `make` output by not duplicating each file in the print out.
> userland: don't print "DEP" for each file

- boards/nrf51dk/src/main.rs
- chips/nrf51/src/clock.rs
- chips/nrf51/src/gpio.rs
- chips/nrf51/src/nvic.rs
There were two issues, one is our fault one is (maybe) LLVM's/Rust's:
1. A few of the register structs were not marked `repr(C)`, which allows Rust/LLVM to freely re-arrange or compress fields and it appears newer versions start doing so.
2. As noted in rust-lang/rust#42248, the resulting assembly from the switch statement in nrf51dk's `with_driver` makes no sense (and causes a hard-fault when `driver_num` is 3) when it's optimized and inlined, so we're marking it `inline(never)` for now until we get to the bottom of it.
> Fix compilation issues on NRF51 resulting from Rust nightly upgrade

- chips/nrf51/src/nvic.rs
- chips/nrf51/src/peripheral_registers.rs
Minor refactoring, changed all memory-mapped I/O structs to have memory layout _#[repr(C, packed)]_ for nrf51dk.
_$ find -type f -exec grep -H 'repr' {} \;
./src/timer.rs:#[repr(C, packed)]
./src/clock.rs:#[repr(C, packed)]
./src/peripheral_registers.rs:#[repr(C, packed)]
./src/peripheral_registers.rs:#[repr(C, packed)]
./src/peripheral_registers.rs:#[repr(C, packed)]
./src/peripheral_registers.rs:#[repr(C, packed)]
./src/peripheral_registers.rs:#[repr(C, packed)]
./src/uart.rs:#[repr(C, packed)]
Binary file ./src/.gpio.rs.swp matches
./src/nvic.rs:#[repr(C, packed)]
./src/gpio.rs:#[repr(C, packed)]_
> Consistent struct representation for nrf51dk

- boards/Makefile.common
This runs `cargo check` to use the Rust compiler to find Rust compilation errors.
Fixes #328
> kernel make: add `make check`

- boards/imix/src/spi_dummy.rs
- capsules/src/fm25cl.rs
- capsules/src/i2c_master_slave_driver.rs
- capsules/src/nrf51822_serialization.rs
- capsules/src/radio.rs
- capsules/src/sdcard.rs
- capsules/src/spi.rs
- capsules/src/virtual_spi.rs
- chips/sam4l/src/spi.rs
- chips/sam4l/src/usart.rs
- kernel/src/hil/spi.rs
We've gone through a couple iterations for how application-specific state is held in capsules. This PR updates all non-virtualized capsules to the
```rust
impl Default for App {
fn default() -> App {
App {
callback: None,
buffer: None,
remaining: 0,
idx: 0,
}
}
}
```
method. It also makes the naming consistent.
Along the way I noticed that the SPI HIL returns a `bool`. I updated that to `ReturnCode`.
> Capsules: Make `struct App {}` consistent

- arch/cortex-m4/src/mpu.rs
- arch/cortex-m4/src/scb.rs
- arch/cortex-m4/src/systick.rs
- boards/hail/src/main.rs
- boards/imix/src/main.rs
- boards/nrf51dk/src/main.rs
- capsules/src/i2c_master_slave_driver.rs
- capsules/src/ltc294x.rs
- capsules/src/ninedof.rs
- capsules/src/radio.rs
- capsules/src/rf233.rs
- chips/sam4l/src/adc.rs
- chips/sam4l/src/ast.rs
- chips/sam4l/src/bpm.rs
- chips/sam4l/src/crccu.rs
- chips/sam4l/src/dma.rs
- chips/sam4l/src/gpio.rs
- chips/sam4l/src/i2c.rs
- chips/sam4l/src/nvic.rs
- chips/sam4l/src/pm.rs
- chips/sam4l/src/scif.rs
- chips/sam4l/src/spi.rs
- chips/sam4l/src/trng.rs
- chips/sam4l/src/usart.rs
- chips/sam4l/src/wdt.rs
This unifies things so that if a lib/mod.rs file has `pub use` we use that path instead of the absolute one.
> Use public kernel path on `use`s

- userland/AppMakefile.mk
- userland/Configuration.mk
- userland/Helpers.mk
- userland/TockLibrary.mk
- userland/examples/build_all.sh
- userland/examples/lua-hello/Makefile
- userland/examples/rf233/rf233.c
- userland/examples/tests/hail/main.c
- userland/examples/tests/mpu_stack_growth/Makefile
- userland/examples/tests/mpu_walk_region/Makefile
- userland/examples/tutorials/03_ble_scan/main.c
- userland/libnrfserialization/Makefile
- userland/libnrfserialization/Makefile.app
- userland/libtock/crt1.c
- userland/libtock/sys.c
- userland/lua53/Makefile
This patch series does two things
1. It cleans up all the warnings currently in Tock userland C
2. It turns on `-Werror` _only_ for `build_all`
The idea of 2 being that we shouldn't let code with warnings into master but it shouldn't interfere with development
> Eliminate all userland warnings

- kernel/src/platform/mpu.rs
- kernel/src/process.rs
When a process has empty IPC regions we were clearing them with an
"empty" `Region`. However, this empty region didn't actually have a
region number, so it was just destroying whichever region had just been
set (usually the grant region, which is extra bad).
This manifested in #395 when a non-empty IPC region was overriden by an empty one, resulting in that region _not_ being exposed to the app, and the app crashing.
This PR fixes the bug by requiring a region number when an "empty" `Region` is created. It's just as non-portable as the rest of the current implementation of MPU regions, but for now it at least fixes the bug.
> Fixes bug in MPU setup with non-empty IPC regions

- userland/examples/build_all.sh
- userland/libtock/console.c
- userland/libtock/console.h
- userland/libtock/nrf51_serialization.c
- userland/libtock/nrf51_serialization.h
- userland/libtock/tock.h
This should at least allow users from #414 to identify when the attempt to write a string fails
> Enforce checking of return values for syscalls

- capsules/src/gpio_async.rs
- capsules/src/lib.rs
- capsules/src/mcp23008.rs
- doc/Syscalls.md
- kernel/src/hil/gpio_async.rs
- kernel/src/hil/mod.rs
- userland/examples/tests/gpio_async/Makefile
- userland/examples/tests/gpio_async/README.md
- userland/examples/tests/gpio_async/main.c
- userland/libtock/gpio_async.c
- userland/libtock/gpio_async.h
This is the GPIO extender from signpost. This driver also includes interrupt support which I tested separately because interrupts are not used on the Signpost platform.
> Add MCP23008 Capsule

- boards/hail/src/main.rs
- boards/imix/src/main.rs
- boards/nrf51dk/src/main.rs
- kernel/src/common/utils.rs
Sacrifices up to a word of memory in order to avoid requiring the caller
to explicitly pass in the size of the type. When we finally get
`size_of` or other intrinsics at compile-time, we'll be able to get rid
of that overhead as well.
For backwards compatibility accepts an optional size argument which is
simply ignored.
> Avoid requiring an explicit size in static_init

- userland/libtock/ltc294x.c
- userland/libtock/ltc294x.h
Currently we do this conversion in the signpost energy library, but I think it's more appropriate to be encapsulated in the userland driver like the other helper functions.
> Added coulomb helper function for ltc294x

- userland/libtock/tock.c
LTO optimizations breaking things continues to teach me more about
how these are supposed to be written. I believe these are now completely
correct.
A little extra regarding yield:
@brghena and I spent a little while talking this through, but this
should properly express to the complier the semantics of what we're
doing.
Our old approach of
push {lr}
svc  0
pop  {pc}
failed in cases where yield is inlined and the link register isn't
live (i.e. during the `while (1) { yield(); }` loop at the end.
It would've been okay if we'd `pop {lr}` instead of `pop {pc}`'d
because then we would've just pushed and popped a garbage value to
the stack, but the better fix is to just express the clobbers to
the compiler and let it sort what what does and doesn't need to be
saved.
Currently tested working …
> Mark inputs and outputs for extended ASM correctly

- doc/reference/trd102-adc.md
Updates to TRD documentation for the ADC.
Pulling this apart from the main ADC PR so that we can have back and forth on it, but still get the ADC stuff merged into Tock to start using it.
> ADC: Starting on TRD updates

- doc/Userland.md
- userland/tools/uncrustify/.gitignore
- userland/tools/uncrustify/uncrustify.cfg
- userland/tools/uncrustify/uncrustify.sh
I suppose it's not the most surprising that different versions would
format things differently. Like rustfmt, just pin to a specific version
and install it automatically on demand
Towards #432.
> style: pin to one version of uncrustify

- boards/Makefile.common
- boards/nrf51dk/src/main.rs
Rust nightly 06-19-17 included LLVM upstream fixes that address an issue
we were running into on Cortex-M0 targets.
https://github.com/rust-lang/rust/issues/42248
> Upgrade Rust nightly

- boards/Makefile.common
This command only needs to be run once, placing it with the install of
the new toolchain means we don't have to remember to put it everywhere
that we possibly invoke rust, plus it gets rid of the `info: already
up to date` message that was printing with every build
Fixes #436.
> build: trigger rustup component during install

- capsules/README.md
- capsules/src/lib.rs
- capsules/src/max17205.rs
- doc/Syscalls.md
- userland/libtock/max17205.c
- userland/libtock/max17205.h
> Add MAX17205 Driver

- boards/Makefile.common
This should fix the build error from #443
> build: explicitly check for rust-src component

- userland/Configuration.mk
This should be a `?=` like everything else, in the interest of allowing
quick command line overrides
> userland: allow runtime override of TOCK_ARCHS

- capsules/README.md
- capsules/src/lib.rs
- capsules/src/pca9544a.rs
- doc/Syscalls.md
- userland/libtock/pca9544a.c
- userland/libtock/pca9544a.h
Driver for an I2C address multiplexing chip.
Signpost uses this to handle having several battery gauges which all have the same I2C address.
> Add PCA9544a Capsule

- capsules/README.md
- capsules/src/fm25cl.rs
- capsules/src/lib.rs
- capsules/src/nonvolatile_storage_driver.rs
- doc/Syscalls.md
- kernel/src/hil/mod.rs
- kernel/src/hil/nonvolatile_storage.rs
- userland/examples/tests/nonvolatile_storage/Makefile
- userland/examples/tests/nonvolatile_storage/main.c
- userland/libtock/internal/nonvolatile_storage.h
- userland/libtock/internal/nonvolatile_storage_internal.c
This adds a nonvolatile storage interface that virtualizes the underlying physical storage and provides both a userspace interface and a kernel interface. It updates the FM25CL FRAM driver to use this interface as well.
1. It allows for a board to restrict which address space of nonvolatile memory (like an FRAM chip) that userspace can access. This allows the kernel to safely share the same nonvolatile storage that userspace uses.
2. It virtualizes access to the storage so that multiple apps can use it.
2. It provides a generic interface for nonvolatile storage so that we have one userspace API/driver and not one for each chip.
1. It doesn't segment nonvolatile storage between apps. Therefore, any app can read and write all of the userspace accessible nonvolatile storage. This is …
> Create a nonvolatile storage interface.

- chips/sam4l/src/flashcalw.rs
- kernel/src/hil/flash.rs
The purpose of this PR is to update the SAM4L flash driver to provide a HIL trait so that capsules can use it. The `Flash` trait exists so I used that one, but made it explicitly for page-level read and writes.
I successfully used this to implement a capsule that allows apps to write their own flash (after disabling the MPU).
The vision is to end up with a stack like this:
```
Userspace
+----------------------------------------------------+
+----------------------------------------------------+
+----------+ +----------------------------+
|          | |                            |
| AppFlash | | Nonvolatile Storage (#430) | Others...
|          | |                            |
+----------+ +----------------------------+
+-------------------------------------------+ …
```
> Flash updates, implement Flash trait for SAM4L

- capsules/README.md
- capsules/src/lib.rs
- capsules/src/nonvolatile_to_pages.rs
NonvolatileToPages takes a read or write of arbitrary length at an arbitrary location and maps it to a series of page read and writes so it works with page based storage.
Want to get this up here so it doesn't get lost, but it relies on #430 and #446 so it won't build against master right now.
> capsules: add tool to handle flash pages (needs #430 and #446)

- capsules/src/rf233.rs
- kernel/src/hil/radio.rs
This PR fixes two issues with the RF233 implementation for the imix platform.
1. Previously, the two functions `payload_offset` and `header_size` independently determine the header size of a packet parameterized by whether the source and destination addresses are long. However, the latter used a mutually exclusize `if`-`else if` branch, which is an error. This PR changes `header_size` to use the correct `if`-`if` structure, and makes `payload_offset` rely on `header_size` for this computation to avoid similar bugs in the future.
2. Also, the two functions `packet_get_length` and `packet_get_pan` previously only return `0` regardless, which is not correct (they should be extracting the relevant fields from the provided packet). This PR extracts the fields from the packet header according …
> Fix if/if bug and possibly implement packet_get_length/pan in RF233

- userland/examples/radio_tx/main.c
- userland/examples/tests/adc_continuous/main.c
- userland/examples/tests/crc/main.c
- userland/libtock/adc.c
- userland/libtock/aes.c
- userland/libtock/alarm_timer.c
- userland/libtock/console.c
- userland/libtock/crc.c
- userland/libtock/radio.c
- userland/libtock/sdcard.c
- userland/libtock/tock.h
This allows `tock.h` to be compatible with `errno.h`.
Fixes #353
> userland: prepend `TOCK_` to error names

- chips/sam4l/src/gpio.rs
By enabling the GPIO before potentially assigning it to a peripheral, we ensure that calling `configure(None)` will put the pin into GPIO mode, rather than leaving it in the current peripheral mode.
> gpio: configure(None) correct behavior. Fixes #464

- arch/cortex-m4/src/scb.rs
Ref: #470
Exposes trusted calls to set/unset the deep sleep bit in Cortex-M4
> Adds calls to enable and disable deep sleep on CM4

- chips/sam4l/src/chip.rs
- chips/sam4l/src/gpio.rs
- chips/sam4l/src/pm.rs
- kernel/src/lib.rs
- kernel/src/platform/mod.rs
Ref #470 
The `prepare_for_sleep` is where chips will determine which sleep state to go into and prepare for it.
On the SAM4L, The basic strategy is to look at the power manager's clock mask register's and compare them against a set of known clock masks that would let us go into deep sleep without preventing any active
peripherals from working.
> Adds a `prepare_for_sleep` method to the Chip trait with implementation for SAM4L

- userland/AppMakefile.mk
- userland/TockLibrary.mk
- userland/tools/uncrustify/uncrustify.sh
Instead of unconditionally formatting all sources, now create a
%.c[c|pp|xx] -> build/format/%.uncrustify mapping for formatted files.
This allows make to do the right thing on only reformat ("rebuild")
when the source file has actually changed.
Addresses Problem 3 from #432.
> style: treat formatted files as built objects

- boards/imix/Makefile
- doc/Getting_Started.md
I was able to `make` but not `make flash` using the updated `imix` v2.0 code in `master`. Comparing with `boards/hail/Makefile`, it seems that the target path was just slightly off. With this change I am able to flash with no issues.
Also, could someone clarify which tockloader version we are supposed to be using? I just did `pip3 install tockloader --user` as per the tockloader repo's suggestions, but the getting started doc specifies a particular version.
- Fixes the imixv2 Makefile to point to the right target, otherwise it expects the binary to be in `target/sam4l/release` and is not able to flash.
- Updates the getting started documentation to reflect the fact that flashing imix v2.0 now requires tockloader.
> Correct the binary path in the imix v2.0 Makefile

- chips/sam4l/src/bpm.rs
- chips/sam4l/src/pm.rs
The default RUN0 only supports up to a 36MHz clock, however most
boards request a 48MHz clock source. The bootloader ASF code was
already changing this, but that was really luck that things were
working
Tested on Hail, no change (as expected).
Tested on Signpost Ambient on top of Amit's uart sleep and fixes the wakeup issue.
> sam4l: power scaling before increasing core speed

- capsules/src/ltc294x.rs
The ltc294x capsule is not working (specifically the configure function) because I2C was not being enabled.
> Enable I2C in Configure Function

- boards/imix/src/main.rs
Correct `set_pin_primary_functions` to properly set PC[08] to USART2 CTS instead of USART2 CLK. Closes #495.
> imix: Correct PC[08] assignment.

- tools/list_boards.sh
Without this, running "make list-boards" gets me an error like:
./tools/list_boards.sh: line 19: [: -eq: unary operator expected
> list_boards.sh: hush a bash warning when not using -1

- chips/sam4l/src/i2c.rs
You can't just disable the clock - it causes the I2C to hang.
Instead call the proper I2CSlave disable function which also disables the clocks.
Tested and working on a signpost initialization procedure.
> Disable i2cslave Perhiperal for Master Transfer

- boards/nrf51dk/src/main.rs
- chips/nrf51/src/ble_advertising_driver.rs
- chips/nrf51/src/radio.rs
- userland/examples/ble_adv/main.c
- userland/examples/ble_scan/Makefile
- userland/examples/ble_scan/main.c
- userland/libtock/ble.c
- userland/libtock/ble.h
Hi,
The major fixes with this PR are:
- Support payload size of 31 bytes instead of 30
- Support passive scanning of advertisements
- Added a sample application for scanning
- Added more inline comments
There are two controversial things in this PR which comes to mind:
- I'm using the radio HIL for callbacks to user-space
- I'm using the same buffer for both scanning and broadcasting (BLE_NONCONN_IND) because these never occur at the same time in current implementation!
Hopefully I managed to rebase properly this time.
--
Niklas A
> BLE advertisement support 31 byte payload and added scanning

- capsules/src/radio.rs
- capsules/src/rf233.rs
- kernel/src/hil/radio.rs
- userland/examples/radio_ack/main.c
- userland/examples/radio_rx/main.c
- userland/examples/radio_rxtx/main.c
- userland/examples/radio_tx/main.c
- userland/libtock/radio.c
Partial fix for #499.
I ended up changing some parts of the `kernel::hil::radio` trait so that length types make sense. Nothing has been done about the missing CRC check, MAC address filtering or faulty MHR parsing.
> RF233: correct offsets and lengths so 1 byte of payload isn't dropped

- boards/imix/src/main.rs
- boards/imix/src/power.rs
On imix, there are several pins which need to be 'detached' whenever we switch the power off for a particular submodule. In this case, by 'detached', I mean configured as a GPIO and pulled down, but pin detachment itself is more abstract than that. When the submodule is turned back on, all of these pins need to be restored to their original functions. When testing the power consumption of each submodule, I need to do quite a few of these detachments/restorations in addition to enabling/disabling the power gate for the module, so I wrote a general purpose API that makes this process much easier.
This functionality has other potential uses for the Signpost platform. I put together a rough first pass at an API that could satisfy both my testing needs and the Signpost application, and am …
> Imix submodule power configuration

- capsules/Cargo.lock
- capsules/README.md
- capsules/src/lib.rs
- capsules/src/nonvolatile_to_pages.rs
- capsules/src/virtual_flash.rs
- chips/sam4l/src/flashcalw.rs
- kernel/src/hil/flash.rs
This adds the `virtual_flash.rs` capsule which mirrors our other virtualized HW capsules. It is needed for any platforms which want to have multiple capsules use underlying flash HW.
> Add Virtual Flash

- userland/libtock/sys.c
_sbrk semantics are to return -1 in case of error or a pointer.
TOCK_ENOMEM is not -1, so newlib treated it as a pointer. A quick readover of
the `malloc_extend_top` implementation in newlib (which is what actually calls
_sbrk [well, _sbrk_r which calls _sbrk]) shows that it checks against -1, then
checks that the new pointer is greater than the old pointer (which a modest
negative number certainly would be), then bumps the internal "top" of allocated
memory to the new pointer and rolls merrily on. This explains the behavior we
were seeing where it seems that allocations never failed, rather the MPU would
eventually trip when we ran off the top of the heap
> userland: fix return of _sbrk

- doc/Getting_Started.md
I just tried to build on my mac and got:
```
~/git/tock $ make
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C boards/hail/
../Makefile.common:62: Required tool `xargo` is out-of-date.
../Makefile.common:63: Running `cargo install cargo-update` and `cargo install-update xargo` in 3 seconds (ctrl-c to cancel)
Updating registry `https://github.com/rust-lang/crates.io-index`
Installing cargo-update v1.1.1
Compiling unicode-xid v0.0.4
Compiling unicode-width v0.1.4
Compiling serde v1.0.10
Compiling embed-resource v1.1.3
Compiling vec_map v0.8.0
Compiling libc v0.2.26
Compiling lazy_static v0.2.8
Compiling regex-syntax v0.4.1
Compiling unicode-segmentation v1.1.0
Compiling semver-parser v0.7.0
Compiling percent-encoding v1.0.0
Compiling utf8-ranges v1.0.0
Compiling strsim v0.6.0 …
```
> doc: add cmake to getting started

- boards/hail/src/main.rs
- boards/imix/src/main.rs
- boards/imixv1/src/main.rs
- chips/sam4l/src/bscif.rs
- chips/sam4l/src/flashcalw.rs
- chips/sam4l/src/i2c.rs
- chips/sam4l/src/lib.rs
- chips/sam4l/src/pm.rs
- chips/sam4l/src/scif.rs
- chips/sam4l/src/spi.rs
- chips/sam4l/src/usart.rs
Adds a `specify_external_oscillator` function, to be called from `main.rs`, which sets both the frequency of the oscillator and whether it starts up quickly or slowly.
This should fix sleeping on Signpost boards (for now) which need a slower startup (for uncertain reasons) or else they do not wake up from sleep. However, since Hail sleeps just fine as is, we don't want to impose the startup penalty on it, and this PR allows Hail (and other hardware) to stay with the faster startup timing.
Also, since I was in there, this PR pulls apart PM and separates functionality into various modules based on the peripheral they correspond to.
Tested on a Hail in all supported system clock modes.
Fixes #300
> Change system clock interface

- userland/libtock/alarm_timer.c
Also implicitly casts the division to a float in case alarm_internal_frequency() returns a non-divisable number, then casts the result back to uint32_t.
This has been tested in a Signpost app and seems to be working properly with the changes.
> Uses Correct Order of Operations to Prevent Internal Timer Overflow

- userland/libtock/ltc294x.c
This was an error. It was in mAh, we should be returning uAh.
> Fix LTC294x counter to charge conversion

- boards/Makefile.common
By default, rustdoc only documents public fields. This is great for users of crates, and less great for developers of crates. This commit tells rustdoc to document everything.
> docs: tell rustdoc to document private fields

- userland/userland_generic.ld
As far as I can tell this is not used.
> userland: remove unused load_info section from .ld

- userland/Configuration.mk
- userland/examples/security_app/main.c
- userland/examples/tests/gpio/main.c
- userland/examples/tests/si7021/main.c
- userland/libtock/alarm_timer.c
- userland/libtock/console.c
- userland/libtock/ltc294x.c
- userland/support/warning_header.h
Inspired by a series of signpost bugs, there are some functions that,
while not inherently unsafe, are often dangerous to use and easy to
replace with something safer. The motivating example here being
`snprintf` in favor of `sprintf`. We could add more in the future*,
but for now this is a scaffolding
*Brad was lobbying for strlen, but that's a bit harder, critically
this warning only applies to _emitted_ function calls, so something
like `foo("buf", strlen("buf"))` would not emit a warning, but that's
a bridge for another day)
> userland: warnings on use of certain functions

- boards/hail/src/io.rs
- boards/imix/src/io.rs
- boards/imixv1/src/io.rs
- chips/sam4l/src/pm.rs
- chips/sam4l/src/usart.rs
- userland/examples/tests/hello_loop/Makefile
- userland/examples/tests/hello_loop/README.md
- userland/examples/tests/hello_loop/main.c
Ref: #470
A step towards automatic low power on the SAM4L.
This change only leaves the USART clock enabled when the USART is currently transmitting or recieving. 
In order to properly deal with transmission through the DMA (which may complete while there are still bytes in the TX buffer), the change adds a check for the TX_EMPTY interrupt.
Merging this change will allow platforms that only use the USART to run applications in deep sleep mode when possible that use the USART. For example, the following simple application will go into deep sleep for all but a few microseconds every five seconds:
```c
int main() {
while(1) {
printf("Hello\n");
delay_ms(5000);
}
}
```
Note, however, that for this to work as expected, other peripherals (which do not yet implement proper clock management) would …
> SAM4L Low Power: Manage USART clocks

- boards/hail/src/io.rs
This makes the `panic!` blink more obvious.
> hail: turn off other leds during panic

- boards/hail/src/main.rs
- boards/imix/src/main.rs
- boards/imixv1/src/main.rs
- kernel/src/sched.rs
This will disable the MPU entirely when the kernel runs.
This also means that `enable_mpu()` does not need to be called in board/main.rs.
> kernel: enable and disable MPU for process

- boards/Makefile.common
For some reason building docs won't generate a target folder if one doesn't already exist.
> make: generate target file if not exist

- boards/hail/src/main.rs
- boards/imix/src/main.rs
- boards/nrf51dk/src/main.rs
- boards/nrf52dk/src/main.rs
- kernel/src/process.rs
Historically the `load_process()` function has been in the board's main.rs file. This has lead to some duplicated code. This PR adds a generic version to process.rs that platforms can use if they wish.
It also updates the imix and hail boards to use the generic version.
> Create a generic and default load_processes() function

- boards/hail/README.md
- doc/Compilation.md
- doc/Getting_Started.md
- doc/Userland.md
- kernel/src/memop.rs
- kernel/src/process.rs
- userland/examples/tests/writeable_flash_regions/Makefile
- userland/examples/tests/writeable_flash_regions/README.md
- userland/examples/tests/writeable_flash_regions/main.c
- userland/libtock/tock.c
- userland/libtock/tock.h
- userland/tools/elf2tbf/Cargo.lock
- userland/tools/elf2tbf/Cargo.toml
- userland/tools/elf2tbf/src/main.rs
This updates the kernel with a new Tock Binary Format header (version 2). The new header includes a `flags` field which can provide app-specific configs for flashed apps.
The two supported flags are:
1. Enable/disable. Tells the kernel to run or not run an application at boot.
2. Sticky. Tells tockloader to not erase the app without --force.
Tockloader has been updated to support this new header.
This PR is marked as blocked so that we can see if there are other changes to the header format we want to add for version 2.
> TBF Header Version 2

- capsules/README.md
- capsules/src/app_flash_driver.rs
- capsules/src/lib.rs
- doc/Syscalls.md
- kernel/src/callback.rs
- kernel/src/process.rs
- userland/examples/tests/app_state/Makefile
- userland/examples/tests/app_state/main.c
- userland/libtock/app_state.c
- userland/libtock/app_state.h
- userland/tools/elf2tbf/src/main.rs
- userland/userland_generic.ld
Provides userspace with a mechanism to write their own flash space.
I need some way to ensure that an app is only trying to write its own space (and not the TBF header). Also, I think this doesn't work if the MPU is enabled, even if an app is writing its own space.
> app flash: allow apps to write their own flash

- boards/imixv1/src/main.rs
- use `PllExternalOscillatorAt48MHz`
- use `kernel::process::load_processes()`
- eliminate size args from `static_init!` calls
This is useful just because I still develop on imixv1 and don't want to
diverge more than necessary from the new board.
> imixv1: merge back some of the changes to imix

- kernel/src/process.rs
The code was assigning Default::default() into allocated memory, which
implies dropping the value that previously lived there. But the "value"
at this point is uninitialized kernel segment memory, and so dropping it
is not intrinsically safe. (Though it works for most types.)
This change switches to writing the container using core::ptr::write,
which is defined as moving its argument *without* dropping the contents
of the target.
> process: fix containers that impl Drop.

- boards/nrf51dk/README.md
The NRF docs pointed you to getting started and getting started pointed you to "board-specific" instructions in these docs.
@niklasad1 could you double-check that I haven't said anything wrong / oversimplified here
> Remove circular references from NRF documentation

- userland/Configuration.mk
- userland/tools/elf2tbf/src/main.rs
The kernel knows how to load processes without PIC information in their binaries, but `elf2tbf` didn't know how to exclude that header. So this excludes that header by default, adding a `-p` argument to include it.
It also adds the `-p` argument to C apps in `userland/`, so there should be no change for apps in practice.
This just sets us up to do Rust apps differently (and evaluate potentially moving the PIC handling code to C as well)
> Make pic information optional in `elf2tbf` through an argument

- boards/Makefile.common
There's an asymmetry right now between userland and kernel, where
in the kernel `make debug` does a different build and in userland
it makes the lst file. We should rectify that interface at some
point, but in the immediate term, it's useful to have any way to
generate an lst file for the kernel
> provide a target to build lst for kernel

- doc/Compilation.md
- kernel/src/process.rs
- userland/tools/elf2tbf/src/main.rs
To help with avoiding unaligned accesses, all TLV blocks are now aligned to 4 bytes. The length field still specifies the length of the Value section, but if that length is not a multiple of 4, there is padding so
that the next header starts on a multiple of 4.
> TBF header: pad all TLV blocks to 4

- arch/cortex-m0/src/lib.rs
- arch/cortex-m4/src/lib.rs
- kernel/src/process.rs
- userland/libtock/crt1.c
This change is step 2 in reconciling how processes are loaded given that they may or may not use the kernel default PIC strategy. This step is a moderate cleanup phase, and I believe ends up leaving relocation related code in only one function in the kernel, basically.
`data_start_pointer` was only being used to set the value of r9 in
`switch_to_user`. However, first, that's dependent on the processes
(i.e. a processes that uses a different PIC strategy will point r9
somewhere else). Second, it was buggy for non-PIC processes (setting r9
to 0 in practice). Finally, we already have this value anyway from the
initial stack pointer in the default PIC strategy.
So, this removes that field, removes setting the r9 value in the kernel,
deferring it to the processes, and uses the initial stack …
> Remove `data_start_pointer` from load_info

- userland/Configuration.mk
1. Don't need to do abspath for elf2tbf.
2. notdir can't escape spaces in path, must use basename instead.
I can't promise I tried everything, but I flashed a kernel and multiple apps on to a board.
> userland: handles spaces in absolute path

- capsules/src/console.rs
- userland/libtock/console.c
Use the common `allow`/`subscribe`/`command` triad to initiate writes in the console driver.
Also added documentation to the console driver capsule.
Fixes #555
> Fix #555: Command to trigger console op

- kernel/src/debug.rs
Without this fix, the debug system never actually writes the string, so you get no debug output.
> Debug needs to issue command -- fixes bug introduced by #560

- boards/Makefile.common
This basically copies the check we use from the userland build.
Fixes #567.
> check gcc version in kernel build too

- capsules/src/mac.rs
There were some straggling unused symbols in the 802.15.4 MAC capsule since encryption is not yet implemented.
> Clean up unused symbols in Mac capsule

- boards/imixv1/src/main.rs
When writing the MAC module, one thing I tried to do was make the boot initialization sequence simpler. It bugs me that there are pieces of code calling methods on the `rf233` device scattered in many places in the initialization code, and the dependencies between each piece of initialization code are not necessarily that explicit. It turns out that the rf233 needs to be `reset` and `start` after the chip is created, otherwise the SPI communication that starts the radio is never sent.
Going forward, I think it's better to make these dependencies explicit, at least with comments for a start.
> Move two lines down to solve initialization order issue

- capsules/src/radio.rs
Slight cleanup following @alevy's comment in the last PR: [remove the unwrap](https://github.com/helena-project/tock/pull/524#discussion_r131992062) in the `RadioDriver` receive callback.
> RadioDriver: remove unwrap from receive callback

- boards/imix/src/main.rs
- capsules/src/lib.rs
- capsules/src/mac.rs
- capsules/src/net/ieee802154.rs
- capsules/src/radio.rs
- capsules/src/rf233.rs
- userland/examples/tests/ieee802154/radio_ack/main.c
- userland/examples/tests/ieee802154/radio_rx/main.c
- userland/libtock/radio.c
This PR implements the incoming and outgoing frame security procedures, save for the actual calls to CCM* encryption/decryption. That will have to wait for CBC encryption to be in mainline. Along the way, it also does the following things:
- Update the userspace code using the radio. I think some of the tiny changes (offsets and lengths and the way they are passed between kernel and userspace) must have gotten lost when the test files were moved.
- Mirror the imixv1 initialization code over to the imix initialization code.
- Remove unnecessary config callback logic from `capsules::mac`: it turns out the radio already does this.
- When parsing headers of secured frames, we must be careful not to try to parse payload IEs. This is accomplished by a flag into the decode function.
- Two …
> ieee802154: MAC security procedure minus CCM*

- boards/imix/README.md
It previously said `make flash`.
I guess at some point we should clean up this nomenclature to say `make program-jtag` or something for the less-frequent case.
> imix/README: use 'make program' to program over USB

- boards/nrf51dk/Makefile
- boards/nrf51dk/Makefile-app
- boards/nrf52dk/Makefile
- boards/nrf52dk/Makefile-app
Hi,
- Removed the flash-full option as it is not used by "root-build system"
- Added error messages when trying program nRF5X using ```program option (USB)``` according to @brghena's suggestion
> added error messages when using program option for nRF5X

- userland/tools/elf2tbf/src/main.rs
Somewhat urgent, @bradjc, but hopefully simple to review.
elf2tbf was assuming the text segment started at 0x80000000 in order to
correctly set the _start symbol. Instead, use whatever the base address
is in the text segment. This is important to make it possible for
the Rust userland to not have to assume a 0x80000000 base.
The change doesn't impact any existing apps since the base address for C process text segments is 0x80000000 anyway right now.
> ELF2TBF: Use text region base addr not a fixed one

- capsules/src/rf233.rs
@ptcrews ran into an issue where frame reception would stop working after the first frame. The "next frame is ready" interrupt (`IRQ_2_RX_START`) would trigger after the previous frame arrived over SPI but before the frame is actually sent to the client. This shorts out the `InternalState::RX_*` flow.
The solution is to only handle interrupts when in states where it is ok to handle them, but not during packet reception or transmission and so on. I pulled out the `config_pending` logic from the `InternalState::READY` state for uniformity. It also make it clearer that interrupts have higher priority than configuration requests.
> rf233: Fix interrupt handling flow

- userland/support/warning_header.h
stdio.h doesn't automatically imply it, and the version in newlib
defines __need___va_list which causes <stdarg.h> to only define
__gnuc_va_list, not va_list. This leads to:
./../../../support/warning_header.h:29:65: error: unknown type name 'va_list'
int vsprintf(char * restrict str, const char * restrict format, va_list ap);
Fix this by including stdarg.h explicitly.
> userland/support/warning_header.h: Include stdarg.h explicitly

- doc/courses/rustconf/README.md
gcc-arm-none-eabi only recommends libnewlib-arm-none-eabi, but doesn't
depend on it. Note the need to install both.
> doc/courses/rustconf/README.md: Document the need for newlib

- capsules/src/ambient_light.rs
- capsules/src/app_flash_driver.rs
- capsules/src/button.rs
- capsules/src/console.rs
- capsules/src/crc.rs
- capsules/src/humidity.rs
- capsules/src/ninedof.rs
- capsules/src/nonvolatile_storage_driver.rs
- capsules/src/rng.rs
- capsules/src/symmetric_encryption.rs
- capsules/src/temperature.rs
- capsules/src/timer.rs
- capsules/src/usb_user.rs
- chips/nrf5x/src/ble_advertising_driver.rs
- kernel/src/process.rs
Implementing `From<process::Error> for ReturnCode` cuts out a bunch of code duplication.
I haven't run `rustfmt` to keep the diff simple. I can run it before merging if this patch is something you want.
> Remove manual conversions from process::Error to ReturnCode

- Makefile
- boards/nrf51dk/README.md
- doc/Getting_Started.md
- Add a usage for empty `make` invocation in the root
- Add an `alldoc` target to mirror the `allboards` target
- Remove board-specific directives from the root
Closes #575 as well.
> makefile: remove default TOCK_BOARD

- chips/sam4l/src/flashcalw.rs
This PR makes two main changes to the SAM4L flash driver:
- Remove the "is flash actually erased check". This was a bit of a hack
since it required the flash to be ready without actually checking it
before issuing the quick page read. In addition, we weren't reading the
correct page and we weren't checking the return value, so this check has
been an NOP so far. We just remove it to keep things simpler.
- Otherwise simplify the driver. This get's rid of state variables that
were set but never checked and consolidates state variables.
This pull request was tested by running the `nonvolatile_storage` userland app in conjunction with commit 93eb229e.
> sam4l: flash: update driver

- doc/Userland.md
[Doc-only]
In reviewing #714, I got to thinking about process behavior, in particular `main`'s return code. Perhaps we should attribute it some significance (e.g. kill processes where `main` failed somehow, maybe respawn if error > 0, kill < 0). Not necessarily a debate to have today, just a thought to let rattle around. In the meantime, be explicit that main should return 0 for forward compatibility.
> doc: clarify that main's return value may change

- kernel/src/common/regs/README.md
#[repr(C, packed)] -> #[repr[C]
> [common_regs] #[repr(packed)] is unsafe since a while go

- boards/hail/src/io.rs
If we're going to use this as an example, lets make it look nice.
> hail: descriptive/consistent names in panic

- boards/Makefile.common
Xargo as of 3.11 expects a bin folder to exist that we don't have. If we just create
it then the tool copy in
https://github.com/japaric/xargo/commit/9787b692be1cb7d3602a4b2d68d4b545af2f5cc2
just works and everything is great.
This pull request might be the wrong way to go, and might not work for everyone. But it's a start.
> make: fix bug in xargo 3.11

- boards/hail/src/io.rs
- boards/imix/src/i2c_dummy.rs
- boards/imix/src/io.rs
- chips/sam4l/src/dma.rs
- chips/sam4l/src/usart.rs
> Revert "sam4l: update usart to use RegManager"

- boards/kernel_layout.ld
The arguments from #289 hold, but #627 didn't quite do this right.
This actually places the stack at the bottom of SRAM:
before:
$ nm hail  | grep [es]stack
20002a90 B _estack
20001a90 B _sstack
after:
$ nm hail  | grep [es]stack
20001000 B _estack
20000000 B _sstack
Tested on hail with a few different mixings of apps.
> kernel: actually move stack to the bottom of sram

- kernel/src/process.rs
Doubles the initial process stack size set by the kernel from 64 bytes to 128 bytes.
If a process is compiled with -O0 (no optimizations) it overflows the
initial stack and runs into a MPU fault.
Running without this commit with a blink app compiled with -O0 instead
of -Os:
```
Kernel panic at /Users/bradjc/git/tock/kernel/src/process.rs:752:
"Process blink had a fault"
Kernel version release-1.0-2018-02-319-g7877ec53
---| Fault Status |---
Data Access Violation:              true
Memory Management Stacking Fault:   true
Invalid State Usage Fault:          true
Forced Hard Fault:                  true
Faulting Memory Address:            0x20003FFC
Fault Status Register (CFSR):       0x00020092
Hard Fault Status Register (HFSR):  0x40000000
---| App Status |---
App: blink   -   [Fault] …
```
> kernel: double initial stack size

- boards/kernel_layout.ld
This slight change to the linker file changes how the linker puts kernel relocate sections into flash. In particular, the linker will now include the relocation section in its overflow calculation so it will now correctly error if the flash section is too large.
fixes #847
This pull request was tested by running hail and blink on hail.
I also changed the hail `chip_layout.ld` file to have a rom region 4 bytes smaller than the `.bin` file that is generated and saw that I got a linker error. This does not happen on master.
> kernel: ld: change how relocate is put in flash

- Makefile
The sensys course is what I point people to for getting started, and we
should ensure that it keeps compiling by adding it to travis. I don't
think it is too much of a burden to keep it up to date since it is
basically the same as hail.
fixes #765
This pull request was tested by running `make allboards`.
> Build the sensys course board file in travis

- doc/Syscalls.md
Just a typo fix in documentation.
> doc/Syscalls.md: replace Hail with TestBoard

- chips/nrf5x/src/timer.rs
We found copy-paste bugs in the get_cc methods. Also exposing more of registers to be accessed from radio. (Separated out from #915)
> Timer updates to prepare for NRF52 connection driver PR

- boards/Makefile.common
- boards/ek-tm4c1294xl/Cargo.toml
- boards/hail/Cargo.toml
- boards/imix/Cargo.toml
- boards/launchxl/Cargo.toml
- boards/nrf51dk/Cargo.toml
- boards/nrf52dk/Cargo.toml
This commit adds a make target for boards called `debug-lst` which
builds the debug version LST file.
It also disables LTO on debug builds since when it is set to true the
debug builds don't compile and throw this error:
```
make debug
Compiling kernel v0.1.0 (file:///Users/bradjc/git/tock/kernel)
Compiling imix v0.1.0 (file:///Users/bradjc/git/tock/boards/imix)
Compiling cortexm4 v0.1.0 (file:///Users/bradjc/git/tock/arch/cortex-m4)
Compiling capsules v0.1.0 (file:///Users/bradjc/git/tock/capsules)
Compiling sam4l v0.1.0 (file:///Users/bradjc/git/tock/chips/sam4l)
error: can't perform LTO when compiling incrementally
error: Could not compile `imix`.
To learn more, run the command again with --verbose.
make: *** [target/thumbv7em-none-eabi/debug/imix] Error 101
```
Fixes #731
This pull …
> boards: debug: build lst seperately

- kernel/src/lib.rs
- kernel/src/process.rs
Hasn't been possible previously, but with some recent fixes to rustfmt it now does not error on process.rs.
This pull request was tested by compiling the hail board.
n/a
> kernel: format process.rs

- boards/ek-tm4c1294xl/src/main.rs
- boards/hail/src/main.rs
- boards/imix/src/main.rs
- boards/launchxl/src/main.rs
- boards/nrf51dk/src/main.rs
- boards/nrf52dk/src/main.rs
- doc/courses/sensys/exercises/board/src/main.rs
- kernel/src/lib.rs
- kernel/src/sched.rs
Some boards may not want to use applications, and therefore do not need
to support IPC. This commit wraps the IPC mechanism passed to the kernel
in an option so that a board can pass in None.
This is motivated by the bootloader, which does not support
applications.
This pull request was tested by running the `rot_` apps on hail.
n/a
> kernel: make IPC optional

- boards/hail/src/main.rs
- boards/imix/src/main.rs
- boards/nrf51dk/src/main.rs
- doc/courses/sensys/exercises/board/src/main.rs
- kernel/src/common/utils.rs
`static_init` does not use the size argument any more, and this cleans up lingering uses.
This pull request was tested by running `make allboards`.
n/a
> static_init: remove lingering size arguments

- chips/sam4l/src/spi.rs
- Move `enable()` to after the check for an early return in
`read_write_bytes()`.
- Return an error if `read_write_bytes()` doesn't do anything (since the
comment says that `SUCCESS` implies the SPI driver is doing something.
- Simplify the code that calculates how long the DMA transaction should
be.
This pull request was tested by compiling hail.
n/a
> sam4l: spi: do not enable without disable

- kernel/src/common/take_cell.rs
The documentation tests for `TakeCell` were out of date, and
reflected behavior of `MapCell`.  Update them to working
examples.
This pull request was tested by running `cargo test`.
- This change is the documentation update.
> Fix documentation tests in take_cell.rs

- capsules/README.md
- capsules/src/lib.rs
- capsules/src/segger_rtt.rs
This provides a "UART" interface that transmits messages using Segger's
RTT protocol.
This pull request was tested by using it successfully on the ADC52832.
n/a
> capsules: add Segger RTT capsule

- doc/Memory_Isolation.md
Fix broken link in "Memory Isolation" doc
> Fix broken link

- boards/ek-tm4c1294xl/src/io.rs
- boards/ek-tm4c1294xl/src/main.rs
- boards/hail/src/io.rs
- boards/imix/src/io.rs
- boards/launchxl/src/io.rs
- boards/launchxl/src/main.rs
- boards/nordic/nrf51dk/src/io.rs
- boards/nordic/nrf51dk/src/main.rs
- boards/nordic/nrf52840dk/src/io.rs
- boards/nordic/nrf52840dk/src/main.rs
- boards/nordic/nrf52dk/src/io.rs
- boards/nordic/nrf52dk/src/main.rs
- doc/courses/sensys/exercises/board/src/io.rs
- doc/courses/sensys/exercises/board/src/main.rs
- kernel/Cargo.lock
- kernel/src/debug.rs
- kernel/src/lib.rs
asm!() is architecture specific, so we shouldn't have it in the kernel crate.
This is part of #985.
n/a
> kernel: remove asm

- tools/build-all-docs.sh
The old method was making a call to `awk` that was too long on linux. This method avoids that. No functionality changed.
Tested that search-index.js looks correct on mac and linux.
This should allow #1019 to pass travis.
This pull request was tested by running the script on both mac and linux.
n/a
> tools: fix build-all-docs script

- arch/cortex-m/src/scb.rs
There are only 3 `SHP` registers, not 12.
This pull request was tested by looking at a lot of datasheets.
Someone to double check.
> arch: scb register map fix

- chips/cc26x2/src/crt1.rs
- chips/cc26x2/src/lib.rs
- chips/cc26xx/src/ccfg.rs
- chips/cc26xx/src/lib.rs
- chips/nrf51/src/crt1.rs
- chips/nrf51/src/lib.rs
- chips/nrf52/src/crt1.rs
- chips/nrf52/src/lib.rs
- chips/sam4l/src/lib.rs
- chips/tm4c129x/src/lib.rs
- doc/Startup.md
- kernel/src/common/utils.rs
- kernel/src/lib.rs
- kernel/src/process.rs
We had been using `#[no_mangle]` which is a workaround to ensure that the compiler doesn't drop important symbols. `#[used]` is designed explicitly for this purpose.
It is also on the path to be stabilized: https://github.com/rust-lang/rust/pull/51363
n/a
> Ensure symbols reach the linker with `#[used]`

- CHANGELOG.md
- boards/ek-tm4c1294xl/src/main.rs
- boards/hail/src/main.rs
- boards/imix/src/main.rs
- boards/launchxl/src/main.rs
- boards/nordic/nrf51dk/src/main.rs
- boards/nordic/nrf52dk_base/Cargo.lock
- boards/nordic/nrf52dk_base/src/lib.rs
- kernel/src/lib.rs
- kernel/src/process.rs
- kernel/src/sched.rs
`HAVE_WORK` is currently a process.rs global static variable. This is probably not what we really want, as it requires `unsafe` to use. This creates a `Kernel` struct and stores the number of callbacks waiting as a member variable in that struct. In the process, I counted 5 uses of `unsafe` that are now gone.
Now, before HAVE_WORK was a `VolatileCell`. I'm not sure why that is needed, so I made it a `NumCell` instead (essentially just a `Cell`). If someone knows why it must be volatile then it can be changed back.
Also, this moves the schedule function to a be a class function of `Process`, where it probably should have been anyway.
This pull request was tested by running hail on hail.
n/a
> kernel: make HAVE_WORK a member variable

- kernel/src/mem.rs
We do not need to use `as_ref()` which requires `unsafe`.
Relevant documentation is here: https://doc.rust-lang.org/1.26.0/core/ptr/struct.Unique.html
This pull request was tested by running the adc test app on hail, and it seems to still work.
n/a
> kernel: use as_ptr() in appslice

- kernel/src/callback.rs
- kernel/src/common/deferred_call.rs
- kernel/src/grant.rs
- kernel/src/lib.rs
- kernel/src/mem.rs
- kernel/src/memop.rs
- kernel/src/platform/mod.rs
- kernel/src/process.rs
- kernel/src/sched.rs
- kernel/src/syscall.rs
- kernel/src/tbfheader.rs
An enhancement to Rust is the `crate` visibility modifier (https://github.com/rust-lang/rust/issues/44660). This can be used instead of `pub` for things which should only be available within the crate, and not publicly available to all users of the crate.
This PR updates the kernel crate to use this in many places where functions and variables shouldn't be accessible outside of the kernel crate.
This is part of tracking issue #1088.
This pull request was tested by compiling. It doesn't actually make any logic changes.
n/a
> Make most of `kernel` crate-visible only, rather than public.

- kernel/src/memop.rs
- kernel/src/process.rs
- kernel/src/sched.rs
This switches the `Process` struct to use `Cell`s rather than mutate itself directly. This has a bit of a size penalty, but makes it possible to remove static buffers in the kernel.
This is pushing towards #1043. To remove the `PROCS` static array, there is no way (that I know of) to do it without removing the use of mutable `&Process` in the kernel. This change brings `Process` inline with other structures in Tock.
This pull request was tested by running hail on hail.
n/a
> kernel: remove the need for &mut Process

- .travis.yml
- README.md
- bors.toml
- doc/CodeReview.md
Rust has spun out their automated build and merge tool bors, [as a service](https://bors.tech/). It looks pretty easy to integrate. I believe basically the contents of this PR plus flipping a switch on the bors website.
The big change that bors provides over our current system is that currently Travis builds when branches are pushed, which considers whether the code will build if merged with master at the time the PR is created. It does not test again at the time the PR is approved, which means if another PR is merged in the interim, merging a PR that passed checks could break the build. This is unlikely to happen often, but [has happened to use before](https://github.com/tock/tock/issues/835). (And, happens to be currently set up to happen again with the split OptionalCell PRs).
The …
> Add bors integration for merging PRs

- doc/Compilation.md
- kernel/src/process.rs
- kernel/src/tbfheader.rs
V1 of the TBF header has been deprecated for a while now, and there is very little chance that any boards still have apps with the old tbf header version.
This also removes the PIC options field that is not supported by the kernel, not standardized, and not something we want the kernel to have to support in the future. It is also, as far as we know, unused.
~~Blocked because #1113 _needs_ to be merged.~~
Fixes #1147.
n/a
> kernel: remove TBF header v1

- libraries/tock-register-interface/CHANGELOG.md
- libraries/tock-register-interface/Cargo.lock
- libraries/tock-register-interface/Cargo.toml
- libraries/tock-register-interface/src/registers.rs
I just hit a case where I wanted to use this. I think it makes sense to add?
> Add read_as_enum() to LocalRegisterCopy

- kernel/src/process.rs
- kernel/src/sched.rs
This is quick change to the scheduler to count timeslice expirations in the `debug` structure when they happen during a `command` system call.
This pull request was tested by running the `app1` from the sensys 2018 tutorial.
n/a
> Account for timeslice expiration during syscalls

- boards/nordic/nrf52840dk/src/main.rs
- boards/nordic/nrf52dk/src/main.rs
The RX pin must be specified last for `UartPins::new()`.
https://github.com/tock/tock/blob/1d8cadd4e45698807c1a9d1a7e8f317fd7a197dc/boards/nordic/nrf52dk_base/src/lib.rs#L69-L73
I tried running `console_timeout` on the nrf52840dk and it didn't do anything, and I tracked it down to this. It looks like the fix is also required on the nrf52dk board, but Amit marked the `console_timeout` test as working, so I'm not sure what to make of that.
n/a
> nrf52[840]dk: correct the ordering of pins

- Makefile
- tools/list_boards.sh
1. Our list of boards in the root makefile wasn't quite correct (didn't account for boards in subdirectories). This updates that.
2. Fix a spelling mistake in list_boards.sh.
3. Simplify list_boards.sh and move the display logic to the makefile with all of the other display text.
I ran `make` and `make list` a few times.
n/a
> root makefile: improve listing boards

- chips/sam4l/src/usart.rs
There was a bug in the ordering of how `receive_automatic` is implemented on the sam4l. Basically, the interrupt was being enabled before it was cleared, causing it to fire too early and essentially put the driver in a state it didn't expect.
~For some reason setting up `receive_automatic` disables the USART nvic interrupt. This doesn't make any sense, but it seems to be consistent. So, we re-enable it so that if there are no other interrupts in the system things keep working.~
I found this by trying to get AT commands to work, and in particular getting AT command responses to work. I then double checked with the nrf serialization driver, and that exhibited the same behavior.
n/a
> sam4l: fix interrupt setup ordering in usart `receive_automatic`

- kernel/src/lib.rs
The kernel has no assembly, and it shouldn't because that is not cross-platform.
n/a
n/a
> kernel: no asm feature

- capsules/README.md
- capsules/src/lib.rs
- capsules/src/virtual_pwm.rs
This provides shared access to PWM hardware, and provides the pin locked in interface for users of a single PWM channel.
~Blocked on #1003~
Tested with ACD52832 board.
n/a
> capsules: add virtual_pwm

- boards/acd52832/src/main.rs
- boards/hail/src/main.rs
- boards/imix/src/components/button.rs
- boards/imix/src/components/gpio.rs
- boards/imix/src/main.rs
- boards/launchxl/src/main.rs
- boards/nordic/nrf52dk_base/Cargo.lock
- boards/nordic/nrf52dk_base/src/lib.rs
- capsules/src/gpio.rs
Each app can now register a callback with the capsule and get a callback when an interrupt happens.
For #1216
Running two copies of `examples/tests/gpio` on hail and seeing two apps get the interrupt.
I think this is good enough for the GPIO capsule driver?
> capsules: gpio: support multiple apps

- kernel/src/hil/uart.rs
This will make the usage of `*_buffer` consistent across HILs.
> kernel/hil: Rename `tx_data, rx_data` to `tx_buffer,rx_buffer` in `uart.rs`

- chips/stm32f446re/src/dma1.rs
Commit `5c55cfb42` introduced the following API change.
```
-    pub fn abort_transfer(&self) -> Option<&'static mut [u8]> {
+    pub fn abort_transfer(&self) -> (Option<&'static mut [u8]>, u32) {
```
This removes the need for `get_transfer_counter` method as the same information
is now returned by the u32 element of the return tuple.
> chips/stm32f446re: Remove `get_transfer_counter` from `dma1.rs`

- doc/Syscalls.md
Based on the conversation on Slack, I learned that there was a previously agreed convention to use the higest bit of `driver_num` for private drivers.
Since I could not find it documented anywhere, this PR documents it.
> doc: Document `driver_num` for private drivers

- arch/cortex-m3/src/lib.rs
- arch/cortex-m4/src/lib.rs
In Tock, a `Process::create` creates a `Process` struct and stores it in the
App Grant region. Within the `Process` struct there is a field `stored_state`
defined as follows.
```
/// State saved on behalf of the process each time the app switches to the
/// kernel.
stored_state:
Cell<<<C as Chip>::UserspaceKernelBoundary as UserspaceKernelBoundary>::StoredState>,
```
For Cortex-M based architecture, the `StoredState` is associated with type
```
/// This holds all of the state that the kernel must keep for the process when
/// the process is not executing.
#[derive(Copy, Clone)]
pub struct CortexMStoredState {
regs: [usize; 8],
yield_pc: usize,
psr: usize,
}
```
The `regs` field refers to the non-hardware stacked registers (r4 thru' r11)
which must be saved and restored on every context …
> arch/{cortex-m4,cortex-m3}: Update documentation for `switch_to_user`

- chips/stm32f4xx/src/dma1.rs
Removes unused import from `chips/stm32f4xx/src/dma1.rs`
> chips/stm32f4xx: Remove unused import

- boards/Makefile.common
The `OBJDUMP` args assumed that the assembly would be thumb, and with RISC-V coming that is no longer true. This checks the target and adds the argument only if "thumb" is in the target name.
I'm not sure if there is a better way to do this. It's incredibly frustrating that objdump either doesn't check for thumb in the elf or the elf doesn't contain enough information to tell objdump.
This pull request was tested by running `make lst` for the hail board and verifying that the assembly in `hail.lst` looks reasonable.
If there is a better way to do this then we should do that.
> make: do not assume thumb arch for lst

- boards/Makefile.common
- tools/build-all-docs.sh
With new architectures being included in Tock we cannot just assume the target will be `thumb*`. This changes the build all docs script to grab the target name from the board being built.
I ran `./tools/build-all-docs.sh` and it completed. I suppose seeing what netlify does will be a better test.
n/a
> docs: Pull target from the board being built

- tools/run_cargo_fix.sh
Runs `cargo fix` on all crates. Useful for updating as rust changes.
I used this when trying to update to a more recent Rust nightly.
n/a
> tools: add cargo fix script

- tools/list_boards.sh
Speeds up considerably with a lot of built boards.
Before:
```
time ./tools/list_boards.sh
nordic/nrf52dk
nordic/nrf52840dk
launchxl
hifive1
hail
nucleo_f429zi
acd52832
imix
nucleo_f446re
real	0m0.948s
user	0m0.139s
sys	0m0.861s
```
After:
```
time ./tools/list_boards.sh
nordic/nrf52dk
nordic/nrf52840dk
launchxl
hifive1
hail
nucleo_f429zi
acd52832
imix
nucleo_f446re
real	0m0.016s
user	0m0.006s
sys	0m0.012s
```
This pull request was tested by running the script on my mac.
Would be good to run this on linux.
> tools: list_boards: limit depth of search

- capsules/src/analog_comparator.rs
- capsules/src/dac.rs
- capsules/src/i2c_master.rs
- capsules/src/net/icmpv6/icmpv6.rs
- capsules/src/net/sixlowpan/sixlowpan_compression.rs
- capsules/src/net/udp/driver.rs
- capsules/src/rf233.rs
- capsules/src/test/aes_ccm.rs
- chips/sam4l/src/acifc.rs
- chips/sam4l/src/adc.rs
- chips/sam4l/src/bscif.rs
- chips/sam4l/src/crccu.rs
- chips/sam4l/src/usart.rs
- kernel/src/common/ring_buffer.rs
- kernel/src/ipc.rs
This is basically the changes recommended by using the `clippy::needless_return` lint.
I think this is a pretty clear code consistency improvement, since we mostly omit the `return` when it is not needed.
This pull request was tested by ensuring travis passes.
n/a
> Remove unneeded `return`s

- arch/cortex-m0/src/lib.rs
Make name consistent with `cortex-{m3,m4}`.
> arch/cortex-m0: Rename `SVC_Handler` to `svc_handler`

- kernel/src/common/mod.rs
Having `RegisterLongName` trait in chip crates allows us to build generic
`structs` and other types such as
```
struct PeripheralSetClear<T>
where
T: RegisterLongName,
{
set: FieldValue<u32, T>,
clear: FieldValue<u32, T>,
}
```
where `T` can refer to `FieldValues` spread across different registers.
This allows us to capture registers associated with a specific function and
build other data structures on top of it.
> kernel/common: Export `RegisterLongName` for use in chip crate

- arch/cortex-m0/src/lib.rs
Alignment issue came up while trying to set a breakpoint and stepping through `svc_handler()`.
> arch/cortex-m0: Add `.align 4` for `svc_handler()`

- chips/arty_e21/Cargo.lock
- chips/arty_e21/src/chip.rs
For some reason, adding the PMP driver causes userspace to fail on the
E21 core running on the Arty FPGA. I don't know why, but reverting this
change seems to allow userspace to run.
The driver should be added back when someone is able to test on the E21.
Symptoms:
- App is loaded, and the kernel switches to the app.
- The first memop syscall is triggered, and execution switches back to
the kernel.
- When the kernel goes to resume the application a fault occurs. I
believe the `mcause` is set to 1 ("Instruction access fault").
- The app goes into a fault state and the kernel panics.
This pull request was tested by running blink on E21 core on FPGA.
Well the PMP driver should be implemented, but that is beyond this PR.
> arty e21: remove PMP driver

- kernel/src/hil/time.rs
For 24-bit clock, `max_tics` should be `(1 << 24) - 1` instead of `(1 << 24)`
> kernel/hil: Minor doc update for time hil

- arch/cortex-m3/src/lib.rs
- arch/cortex-m4/src/lib.rs
- kernel/src/debug.rs
Since `TOCK_KERNEL_VERSION` only gets set in the board makefile, running cargo commands manually often times ends with an error that `TOCK_KERNEL_VERSION` is not set. Now we choose a reasonable default so that things like running `cargo clippy` don't result in errors.
This pull request was tested by travis.
N/A
> replace env! with option_env!

- tools/check-all-links.sh
This script scans all markdown files to find broken links. It works OK, but awesome_bot does not handle code blocks properly so there are many false negatives.
I've had this in a branch for a while, not sure there isn't a good reason to just have it in the tools folder.
This pull request was tested by running it at various times and having the pull requests created from its output merged.
n/a
> tools: add link checking script

- boards/Makefile.common
The board shared Makefile has changed a few times, and this just goes through it and cleans it up a bit.
This pull request was tested by compiling Hail.
I would really like to rename `Makefile.common` to `Common.mk` so that source highlighting works.
> make: freshen up board Makefile

- arch/rv32i/src/syscall.rs
This allows for syscalls on the hifive1 board to not panic, and the hello_world program to run successfully.
I tested this with the hello_world program on the hifive1 rev a board.
> Add hifive1 support for user application

- chips/sifive/src/pwm.rs
The mmio [here](https://sifive.cdn.prismic.io/sifive%2F500a69f8-af3a-4fd9-927f-10ca77077532_fe310-g000.pdf) on page 90 states that the first and third words are reserved. This simply changes the mapping to observe this.
> SiFive: PWM: Slight MMIO address correction

- tools/svd2regs.nix
Due to a change in Nix, `setuptools` is no longer available by default. 
Upstream issue [#68314](https://github.com/NixOS/nixpkgs/pull/68314)
> tools: Add `setuptools` to `svd2regs.nix` generated environment

- kernel/src/common/utils.rs
One does not need an `unsafe` block to define an `unsafe impl` and even `#![forbid(unsafe_code)]` does not prevent an exported macro from injecting such a trait implementation.
To at least prevent capsules from calling `create_capability!`, this adds an explict `#[allow(unsafe_code)]` which will conflict with the `#![forbid(unsafe_code)]` marker.
> Ensure the create_capability! macro cannot be called from capsules

- boards/Makefile.common
- Remove extra `:` from `clean:` target
- Remove extra `release:` target as it seems to be declared twice
> boards/Makefile.common: Minor cleanup

- libraries/tock-register-interface/CHANGELOG.md
- libraries/tock-register-interface/Cargo.toml
- libraries/tock-register-interface/README.md
- libraries/tock-register-interface/src/macros.rs
The current version of the `register_structs!` macro is not usable in `no_std`
libraries or binaries that implement `#![feature(custom_test_frameworks)]`.
Current `register_structs!` definitions will break the test execution because
they emit unit tests with the `#[test]` attribute macro, which depends on the
`std` test crate which isn't there and can't be used in `no_std`:
```
error[E0463]: can't find crate for `test`
| 
::: <::core::macros::builtin::test macros>:1:1
|
1  |    ($ item : item) => { }
|    ---------------------- in this expansion of `#[test]`
--> <::tock_registers::macros::register_structs macros>:11:49
|
1  |  / { $ ($ (# [$ attr : meta]) * $ name : ident { $ ($ fields : tt) * }), * } =>
2  |  | {
3  |  |     $
4  |  |     ($ crate :: register_fields !
...   |
11 |  | …
```
> register_structs!: Fix breakage of custom_test_frameworks

- kernel/src/process.rs
- kernel/src/sched.rs
This accidentally got removed when refactoring how context switches are handled.
Regression likely from #1318.
I tested this by running the list command with the process console.
n/a
> Fix counting the number of syscalls a process has called.

- boards/arty-e21/src/main.rs
- chips/arty_e21/src/chip.rs
This removes the assembly for disabling the PMP, uses the PMP driver when running apps, and maximizes the RAM available to processes.
The blink app still runs on the arty-e21 with this change. I had to increase the app ram to make it work, however.
n/a
> arty-e21: enable PMP

- capsules/src/process_console.rs
- kernel/src/introspection.rs
- kernel/src/lib.rs
- kernel/src/process.rs
If a process's fault response is set to "Restart", then currently that process is unconditionally restarted if it crashes. This PR adds a trait so that boards can specify the policy the kernel should use when deciding whether to restart an app or not. There is an Always option to match what we have now, and I also implemented a very simple threshold approach where an app will only be restarted a certain number of times.
This is part of #1082.
I tested this earlier, but need to test with the recent PR merges.
Thoughts?
> kernel: Add trait for process restart policies

- boards/components/src/nrf51822.rs
- boards/hail/src/main.rs
- boards/imix/src/main.rs
- capsules/src/nrf51822_serialization.rs
This updates the nrf serialization capsule to allow apps that use it to restart successfully.
Part of #1082
This pull request was tested by restarting the hail app on hail using the process console.
n/a
> nRF51 Serialization: Support restarting apps

- kernel/src/sched.rs
As we get closer to finishing #1082, I've been testing restarting various apps and found that caching the appid in the main loop can lead to errors since the appid can change if a process restarts. The issue happens when:
1. an app is executed and crashes during its execution
1. the main loop handles this and restarts it
1. its appid has now changed
1. the scheduler loop re-runs the process
1. the process calls a syscall, but when the kernel loop handles that syscall it uses the process's old cached appid
I think this is fine to merge ahead of the other #1082 changes, but at least it is easier to review separated out in this PR.
Using the crash_dummy app to verify that the app restarts correctly.
n/a
> kernel: don't cache the process appid in main loop

- kernel/src/process.rs
- kernel/src/sched.rs
Saving the last syscall a process called was accidentally dropped in 351c22cf0e4bfabdd4aff77217afa2611ae2f703 during a refactor of the interface between processes and the kernel loop. This restores recording the last syscall.
Relevant to #1641 
This pull request was tested by travis.
n/a
> kernel: Fix recording last syscall

- doc/wg/opentitan.md
Since robust RISC-V support for libtock-rs is essential to the OpenTitan effort, the working group has agreed it should be added to the charter in the same way that rv32i arch support is.
n/a
Any comments or feedback?
> doc: wg: OpenTitan: Update charter with note about libtock-rs

- capsules/src/process_console.rs
- kernel/src/sched.rs
With the updates to AppId, we no longer need to manually expose the index of a process in the processes array to get its ID. This makes it possible to make both versions of process_each in the kernel the same.
Also, this prohibits users of this interface from using the processes array index as an identifier (which it no longer is).
Thanks to @hudson-ayers for pointing this out.
I ran the process console on hail and ensured that the process id changed after faulting the app and having it restart.
n/a
> kernel: stdize process_each and process_each_cap

- capsules/src/process_console.rs
- kernel/src/introspection.rs
Add a mechanism for the process console to show a rough idea of how many system resources a process is using by showing how many grants have been setup for it.
The "list" command in the process console now outputs:
```
PID     Name                Quanta  Syscalls  Dropped Callbacks  Restarts    State  Grants
0	hail                     0      3078                  0         0  Yielded    9/13
1	hello_loop               0       348                  0         0  Yielded    2/13
```
This pull request was tested by running "list" on hail with the two apps you see above installed.
n/a
> kernel+process console: add grant usage

- boards/Makefile.common
#1660 causes the kernel to panic on Hail.
I don't know why, but I git bisected back to this change.
This pull request was tested by running Blink on Hail.
We should merge this and then re-evaluate #1660.
> Revert PR #1660

- capsules/src/process_console.rs
This avoids a potential issue with a virtual uart for the process console. Since the console echos characters to the console itself, but uses `debug!()` for a majority of its printouts, the last echoed newline can get stuck in the virtual uart queue behind the debug!() output, causing slightly malformed output in the terminal. This makes sure that the newline has been echoed before calling any debug!() commands.
This fixes #1569.
This pull request was tested by running the process console on hail and verifying the output looks right.
n/a
> capsule: process console: fix printout ordering

- doc/TockBinaryFormat.md
1. Corrected typo `16 byte specifier` to `16 bit specifier`
2. I would like to propose that we consider making TLV entries that have highest bit of the 16-bit tag specifier set for private use similar to how we do for [`driver_num`](https://github.com/tock/tock/blob/master/doc/Syscalls.md#allocated-driver-numbers)  Motivating reasons are -
- This allows us to experiment with different process loading models
- Private TLV entries can be used for adding vendor specific metadata such as cryptographic signatures
> [RFC] Private TBF TLV tag entry

- kernel/src/grant.rs
- kernel/src/process.rs
The presence of Process Control Block in grant memory region was implicit. This commit updates the comments to reflect that.
> kernel: Update comments to mention Process Control Block

- arch/rv32i/Cargo.toml
- chips/cc26x2/Cargo.toml
- chips/lowrisc/Cargo.toml
- chips/nrf52/Cargo.toml
- chips/nrf52832/Cargo.toml
- chips/nrf52840/Cargo.toml
- chips/sam4l/Cargo.toml
- chips/stm32f303xc/Cargo.toml
- chips/stm32f429zi/Cargo.toml
- chips/stm32f446re/Cargo.toml
- chips/stm32f4xx/Cargo.toml
- libraries/tock-rt0/Cargo.toml
- libraries/tock-rt0/src/lib.rs
There are two changes in this PR.
1. Tree-wide rename of `tock_rt0` to `tock-rt0`. This makes it consistent with other `tock-*` crate names.
2. Rename parameters to `zero_bss` to make it consistent with `init_data`.
> `tock-rt0` related cosmetic changes.

- capsules/src/usb/descriptors.rs
This allows the USB tests to work for me on mac with imix.
I found this by trying to get the tools/usb tests to work. Without this, they fail with something like:
```
thread 'main' panicked at 'Claiming interface: NotFound', src/main.rs:70:5
```
because this line fails:
```
dh.claim_interface(0).expect("Claiming interface");
```
I then tried the same test but using an FTDI chip...which didn't work either but got past the claim interface step. I then compared the output of `lsusb` and changed the imix setup to match until it worked. This was the necessary change.
My guess is that maybe linux is more forgiving with this value than mac?
This pull request was tested by running the tools/usb tests with imix.
It would be great to verify this still works on linux. Try the sam4l-usb branch on …
> capsules: usb: change config descriptor to 1

- chips/sam4l/src/usbc/mod.rs
1. The `OkSetAddress` return type was split off from `Ok`, but not added to the return code handler for the SAM4L. This puts it back.
2. The capsule uses 64 byte buffers, while the sam4l driver originally only used 8 byte buffers. Since we only seem to use the pointer address in the driver, and not the actual length of the buffer, I think it should be fine if the buffers are too long.
This pull request was tested by running the usb test on imix and verifying that my laptop recognizes the USB device.
n/a
> sam4l: usb: handle return code, long buffers

- chips/nrf52/src/usbd.rs
Debug statements at the beginning of the USB driver init process conflict with using the USB stack for UART/debug!(), since those debug outputs cause the USB driver to try to start sending before it is fully initialized. Eventually, an assertion fails and everything crashes.
They are also a little noisy for users not debugging the USB stack.
This pull request was tested by getting CDC working on the nano33ble board.
n/a
> nrf52: usb: do not print debug!() info on startup

- chips/nrf52/src/usbd.rs
While running a modified `printf_long` test app that prints a long string in a loop on nano33ble, I got an assertion failure:
```
Kernel panic at chips/nrf52/src/usbd.rs:1749:
"assertion failed: `(left == right)`
left: `Some(InData)`,
right: `Some(Init)`"
Kernel version release-1.5-500-g9c520bd6b
```
This happens because the resume_in function was only checking the state of the DMA, but not of the IN endpoint, which might be finished with DMA but the entire transfer hasn't finished. I think this wasn't occurring before because with short IN transfers, the end of the DMA and the end of the transfer occur very close to each other and the endpoint wasn't in the `InData` state very long. However, with a longer transfer the `InData` state is longer and thus this assertion could fail.
The fix …
> nrf52: usb: better check state on IN resume

- kernel/src/process.rs
- kernel/src/tbfheader.rs
I was testing Tockloader, and a bug I introduced caused the header_len field to be 14 (when it should have been 16). This caused the kernel to give me an internal kernel error, which is against the threat model. This change fixes that issue, and gets the TBF parsing logic inline with the threat model.
The main change is being much more clear about what errors can be returned with doing the initial parsing of the tbf header in flash. Now there are only two options: we are at the end of apps, or we return the length of the entire app (which is a trusted field). This allows us to more confidently stop parsing for apps, as well as skip over invalid apps.
I tested this with tockloader to corrupt the header length field of an app, and it no longer causes an internal error. Additionally, I …
> kernel: TBF parsing: match the threat model

- kernel/src/grant.rs
This changes how grant allocation is structured in grant.rs so that the
allocation function does not take a copy of the data to be written when
creating a new grant. This data can be large if the grant region is
large, and it can cause a stack overflow when the allocate function is
called.
The change is pretty simple, but I'm not sure if there is some subtle reason to not do it this way.
Fixes the IPC stack overflow issue found in #1933. Replaces #1976.
Running the hail app on hail.
n/a
> kernel: grant: do not pass T::default()

- kernel/src/process.rs
If an app is compiled for a fixed address, then we do not need to custom make an LST file based on where it actually executed. The `make lst` command will work just fine. This updates the message that is printed on a panic for apps which are compiled with fixed addresses.
This pull request was tested by verifying the correct message is printed on hail.
n/a
Our example panic printout is still valid since the PIC app version did not change.
> kernel: process: omit debug addrs for fixed apps

- doc/Porting.md
Markdown template for requirements for adding a new platform.
Copying it into an open PR.
n/a
> docs: porting: add new platform checklist

- kernel/src/sched/priority.rs
Function is now "continue" instead of "break".
This pull request was tested on the arty-e21.
n/a
> kernel: sched: priority: invert logic

- kernel/src/sched.rs
If the timeslice is used up, return the total timeslice length not the amount of time remaining.
This pull request was tested by running imix+whileone on imix.
n/a
> kernel: return correct time used

- capsules/src/fxos8700cq.rs
Enabling just the magnetometer causes the accelerometer to stop working.
We never tested the magnetometer at the same time before and never
noticed this.
This pull request was tested by running sensors app on hail.
n/a
> capsules: fxo: need to enable both mag and accel

- kernel/src/hil/uart.rs
Several grammar mistakes in the Uart HIL were corrected.
> hil: uart: fix grammar mistakes in comments

- kernel/src/process.rs
If a process restarts we need to setup the MPU based on the original app break and not the one the app had when it crashed.
If an app shrank its memory before crashing then not doing this causes an immediate MPU fault if the kernel puts the stack outside of the app's old memory region.
If an app grew its memory before crashing then not doing this causes a security issue since an app can grow its heap, crash, then restart and have access to memory above its app break address.
This pull request was tested by using the stack test 01 app on hail with the bug in libtock-c that causes the app to crash.
n/a
> kernel: process: reconfigure mpu on restart

- libraries/tock-register-interface/src/registers.rs
For u128 type.
I'm using this type to define a very wide bitfield type and need the impl.
> Add missing IntLike implementation

- libraries/tock-register-interface/src/registers.rs
Necessary for 32 or 64 bit CSRs on RISC-V platforms.
Part of #2299.
n/a
> library: registers: support usize

- kernel/src/component.rs
- kernel/src/lib.rs
- kernel/src/platform/mpu.rs
Re: #1654
This feature doesn't _seem_ to be making much progress in Rust: https://github.com/rust-lang/rust/issues/29661.
Also, that was easy.
travis
n/a
> Remove associated_type_defaults feature

- boards/earlgrey-nexysvideo/src/main.rs
- boards/hifive1/src/main.rs
- boards/litex/arty/src/main.rs
- boards/litex/sim/src/main.rs
- capsules/src/low_level_debug/mod.rs
- doc/syscalls/00008_low_level_debug.md
Ran `make prepush`. I don't currently have the ability to test `LowLevelDebug` on hardware, unfortunately.
*I don't see how these changes could go wrong...*
> Migrate the LowLevelDebug capsule to the Tock 2.0 syscall API.

- arch/cortex-m/src/syscall.rs
- arch/rv32i/src/syscall.rs
- kernel/src/syscall.rs
Rather than a separate helper function, use a `From` pattern. This is more rust-y.
Backported from 2.0 branch.
Why? This will make the 2.0 diff easier to read, because the relevant code will show an inline diff, rather than just seeing one block of code deleted and a different block added.
travis
n/a
> kernel: syscall: use `from` fn

- chips/msp432/src/chip.rs
- chips/msp432/src/i2c.rs
- chips/msp432/src/lib.rs
- chips/msp432/src/usci.rs
This PR adds support for I2C on the MSP432. The implementation is done without the usage of DMA since the MSP432 has only 8 DMA channel and 1 I2C bus would require 2 channels (TX and RX). Due to the fact that in most of the cases only a few bytes are transmitted over I2C I thought it would be better to handle the complete implementation via interrupts and save the DMA channels for other peripherals.
Tested on the evaluation board using a [DS1621 temperature sensor](https://pdfserv.maximintegrated.com/en/ds/DS1621.pdf) as slave and the sensor example as application. 
* Is the no-DMA approach ok/fine? Or should I rewrite the driver to use DMA channels?
* For testing I wrote a capsule driver for the DS1621 chip. It's a very simple temperature sensor which works with I2C. Also not all …
> MSP432 I2C driver

- .gitignore
- .gitmodules
- Makefile
I'm trying to use Tock as a dependency for the Tock bootloader. Here is an example Cargo.toml file:
```
[package]
name = "nano33-bootloader"
version = "0.1.0"
authors = ["Tock Project Developers <tock-dev@googlegroups.com>"]
build = "build.rs"
edition = "2018"
[dependencies]
cortexm4 = { git = "https://github.com/tock/tock", branch = "master" }
capsules = { git = "https://github.com/tock/tock", branch = "master" }
kernel = { git = "https://github.com/tock/tock", branch = "master" }
nrf52 = { git = "https://github.com/tock/tock", branch = "master" }
nrf52840 = { git = "https://github.com/tock/tock", branch = "master" }
components = { git = "https://github.com/tock/tock", branch = "master" }
nrf52_components = { git = "https://github.com/tock/tock", branch = "master" }
bootloader = { path = …
```
> Make out-of-tree builds easier

- arch/cortex-m/src/mpu.rs
When determining if a `brk()` call is valid for a process, the MPU has to determine if a subregion (1/8th of the entire app memory region) will cover the new app break address _without_ also including the kernel reserved grant region. If so, it configures the MPU and approves the new app_brk.
Before this math was incorrect if the app break happened to fall on one of the subregion boundaries. The calculation would include an extra region, and if that extra region happened to include the grant region then the brk() would fail, even though it should have been valid. This fixes the calculation to not over-include subregions in that edge case.
Correct panic print:
```
App: no_grant_space   -   [Yielded]
Events Queued: 0   Syscall Count: 6   Dropped Callback Count: 0
Restart Count: 0
Last …
```
> arch: cortex: fix MPU rounding calculation

- shell.nix
shell.nix provides a two-year old version of tockloader.   I was hoping that simply updating it would allow me to interact with a Tock kernel loaded on a Nucleo-F429zi board, but I have not yet gotten this to work.
> Bump tockloader to version 1.6.0

- arch/cortex-m/src/lib.rs
Minor textual change in cortex-m panic handler. Saying "no faults detected" when the a process faulted is a little confusing.
This mostly mirrors the rv32i implementation.
travis
n/a
> arch: cortex-m: clarify panic

- boards/acd52832/Makefile
- boards/arty_e21/Makefile
- boards/clue_nrf52840/Makefile
- boards/earlgrey-nexysvideo/Makefile
- boards/hail/Makefile
- boards/hifive1/Makefile
- boards/imix/Makefile
- boards/imxrt1050-evkb/Makefile
- boards/microbit_v2/Makefile
- boards/msp_exp432p401r/Makefile
- boards/nano33ble/Makefile
- boards/nordic/nrf52840_dongle/Makefile
- boards/nordic/nrf52840dk/Makefile
- boards/nordic/nrf52dk/Makefile
- boards/nucleo_f429zi/Makefile
- boards/nucleo_f446re/Makefile
- boards/redboard_artemis_nano/Makefile
- boards/stm32f3discovery/Makefile
- boards/stm32f412gdiscovery/Makefile
- boards/teensy40/Makefile
- boards/weact_f401ccu6/Makefile
- doc/Design.md
- doc/Getting_Started.md
- doc/Porting.md
Tock has had a long standing convention of two makefile targets for boards to load a kernel onto a board.
1. flash: Uses JTAG to flash the kernel.
1. program: Uses UART and a bootloader to flash the kernel.
This is helpful because some boards support both but require different hardware, and it gives the user some idea of what tools will be needed to load the kernel.
However, new users must figure out which is appropriate if a board supports both. Often there is one target that experienced users just know to use, and we should make this more clear to new users. Also, having different targets on different boards complicates writing a common tutorial guide for multiple platforms.
This patch adds a new target `make install` that just uses the default for the platform. The expectation is that …
> RFC: Add `install` make target for boards

- kernel/src/process.rs
- kernel/src/sched.rs
- kernel/src/syscall.rs
sched.rs and process.rs had several functions marked entirely `unsafe`, resulting in hundreds of lines of code where unsafe operations were allowed and no clear "ownership" of where the unsafe operations were actually being checked.
This PR:
1. Significantly reduces the LoC where `unsafe` is implicitly allowed, and 
2. Tries to clarify where we are doing checks to ensure the unsafe operations are OK.
RFC:
In Tock we try to define `unsafe` as strictly "memory unsafe", not "sensitive function that should be called carefully". I argue that the process.X functions that used to be marked `unsafe` are doing the required checks to ensure that they are memory safe, and therefore shouldn't be marked `unsafe`. I think I was the one who asked for `set_byte()` to be marked `unsafe`, but I think I was …
> RFC: kernel: change `unsafe` handling

- kernel/src/sched.rs
If a process is stopped after faulting, it ends up in the `Faulted` state. Then, if that process still has time in its timeslice remaining, do_process will try to run it again where it hits a panic because the kernel has tried to run a faulted/terminated process. To avoid this we must check if a process actually has any work to do before trying to run it according to its state.
This patch has the side effect that a yield-ed process with nothing to do will no longer hit the yield -> next_task() -> None check in the do_process match statement. I believe this does not matter because both cases result in a break, and there is no way for a process to have work scheduled for it between the new check and the existing yield case check.
Trying the Stop fault response on the nano33ble and seeing …
> kernel: sched: check for process.ready()

- capsules/src/ble_advertising_driver.rs
- capsules/src/console.rs
- capsules/src/crc.rs
- capsules/src/hmac.rs
- capsules/src/ieee802154/driver.rs
- capsules/src/max17205.rs
- capsules/src/net/udp/driver.rs
- capsules/src/screen.rs
- capsules/src/text_screen.rs
- capsules/src/usb/usb_user.rs
- doc/Syscalls.md
- kernel/src/errorcode.rs
- kernel/src/lib.rs
This switches error handling between the kernel and userspace to use the same number <-> error mapping as ErrorCode uses.
Part of #2320 and #2449
Userspace drivers need to be updated to use the new error numbers.
todo
This pull request still needs...
> Define StatusCode which uses ErrorCode's numeric encoding

- doc/wg/core/notes/core-notes-2021-06-04.md
[Rendered](https://github.com/jrvanwhy/tock/blob/core-notes-2021-06-04/doc/wg/core/notes/core-notes-2021-06-04.md)
Add notes from last Friday's core WG meeting.
> Add core WG notes for 2021-06-04.

- kernel/src/driver.rs
Use `process_id` instead of app or app_id
Use `which` for the id parameter for all three functions
> Rename Driver trait parameters for consistency

- kernel/src/hil/gpio.rs
Derive Copy and Clone on the remaining 2 out of 5 enums on the gpio hil trait.
We have some downstream code that puts these enums in a `Cell` so having `Copy` is very nice
None
> hil/gpio: add Copy and Clone to enums

- arch/cortex-m/src/syscall.rs
If the stack pointer is really large the sp + frame_size arithmetic can overflow, negating the check. Use .saturating_add() instead.
In the print context function rather than returning we now use dummy values so the user still gets the register printout for what _is_ valid.
Also check for 4 byte alignment. I think that is a good idea.
I found this by playing with the new tockloader features: `tockloader tbf-delete-tlv 8` and `tockloader tbf-modify-tlv 1 init_fn_offset 53`. I found that if I corrupted the init fn offset in the right way I got a kernel crash.
Running c_hello with a corrupted init fn offset and verifying the printout works as expected. Looks like:
```
Initialization complete. Entering main loop.
Kernel version: release-2.0-rc1
Welcome to the process console.
Valid commands …
```
> arch: cortex-m: defend against large stack pointer

- doc/reference/trd-uart.md
Fix a few punctuations issues in uart.trd. Viewed rendered version in github, and it looks correct
> Correct punctuation issues in trd-uart.md

- kernel/src/platform/mpu.rs
Clean up comment now that https://github.com/rust-lang/rust/issues/65774 has been closed.
I tried just using `()` and I got a compiler error this time.
n/a
> kernel: mpu: Cleanup the comment for the default config type

- doc/wg/core/notes/core-notes-2021-11-05.md
[Rendered](https://github.com/jrvanwhy/tock/blob/core-notes-2021-11-05/doc/wg/core/notes/core-notes-2021-11-05.md)
New record for longest meeting notes!
> Add core WG notes for 2021-11-05.

- kernel/src/memop.rs
- kernel/src/process.rs
- kernel/src/process_standard.rs
- kernel/src/process_utilities.rs
No longer need individual functions since `get_addresses()` provides them all.
This PR might look familiar since it was merged before, but not into master. #2862
travis
n/a
> kernel: remove duplicate address functions

- doc/threat_model/README.md
This note predates Tock 2.0, and is no longer correct. Tock 2.0 implements the threat model as written.
Looked at the [rendered](https://github.com/jrvanwhy/tock/tree/rm-threat-model-warning/doc/threat_model) document.
> Remove the threat model's "not yet implemented" note.

- libraries/tock-cells/src/lib.rs
- libraries/tock-cells/src/optional_cell.rs
Remove unstable feature and just implement the helper function (`contains()`) directly.
We don't need to strictly do this, but the tracking issue for stabilization (https://github.com/rust-lang/rust/issues/62358) took a bit of a downward turn and maybe we shouldn't wait around for it.
travis
n/a
> libraries: cells: remove option_result_contains

- boards/Makefile.common
It turns out that doing `make VERBOSE=1` completely breaks the build. To avoid that mistake in the future, this patch makes both `make V=1` and `make VERBOSE=1` run the build with verbose flags.
Inspired by #2957.
Running make.
n/a
> make: add support for VERBOSE=1

- doc/reference/trd106-completion-codes.md
Based on discussion in https://github.com/tock/libtock-rs/pull/347. This aims to define little about the `exit` syscall other than the common convention that zero indicates success, and non-zero indicates some sort of failure.
[Rendered](https://github.com/kupiakos/tock/blob/trd106/doc/reference/trd106-completion-codes.md)
> Propose a draft TRD for app completion codes

- Makefile
- boards/Makefile.common
Tock uses different flags in CI so that warnings throw errors, while during normal development warnings are OK. We used the CI env variable to control this, however, this conflates Tock's policy on warnings in CI with running in _any_ CI. That is, a fork of Tock also ends up using Tock's CI policy on warnings, because CI tools tend to set the $CI variable as well.
This patch renames our variable to be more clear of what our use is. In theory we can dissallow warnings while not being in CI.
Fixes #3050.
travis
As noted in https://github.com/tock/tock/issues/3050#issuecomment-1145066328 we may be relying on the fact that github actions will set the CI variable even if we don't do it explicitly. Since we are changing the name in this PR, it's possible we will not be preventing warnings when …
> build: change `$CI` to `$NOWARNINGS`

- doc/TockBinaryFormat.md
Read and access IDs are 4 bytes each.
@alistair23 
Implementing support in tockloader.
n/a
> doc: tbf: Fix Persistent ACL doc

- doc/TockBinaryFormat.md
The format did not match the implementation in elf2tab.
@alistair23  is this correct?
Implementing support in tockloader.
n/a
> doc: tbf: Fix Permissions TLV documentation

- boards/redboard_artemis_nano/src/main.rs
- chips/apollo3/src/lib.rs
This reverts commit 190f2146c267b0383ca060fd908e8db99d8dcf23, reversing changes made to c16260b0e25c79e6703dbc2111c42cd08ff7fb31.
Per #3139 
n/a
n/a
> Revert "boards/redboard_artemis: Workaround Hard Fault Exception"

- arch/cortex-m/src/mpu.rs
Use .ok_or() instead of a match.
travis
n/a
> cortex-m: mpu: simplify error check

- arch/cortex-m/src/mpu.rs
The MPU should not make decisions about how much memory to give to a process, the kernel should decide.
It is not clear to me why this check if the kernel does not need any process memory then give the process all of the memory was included.
Quickly using hail.
Does anyone know if this covers a specific use case? The caller should just request the full amount of RAM rather than relying on the MPU to make this decision.
> cortex-m: mpu: do not give all memory to process in certain case

- doc/Porting.md
After changing all of the components we no longer need the warning about components being singletons. Also updated the examples to match the current code.
n/a
n/a
> doc: update porting guide with component updates

- doc/syscalls/00000_alarm.md
Previously, the documentation would still state a single u32 value as return value, the number of supported notifications. However, this is not  in sync with the Tock 2.x tree as only one concurrent timer is supported (at least for libtock-rs).
> Doc: Update DRIVER_CHECK system call for alarm capsule

- doc/reference/trd-legal.md
Indicate that vendored files are exempt for the policy, update the examples, and add "Copyright Tock Contributors" to the examples.
My `git` isn't set up to push to `tock/tock` directly so I'm sending this as a PR.
> License policy 2023-01-23 core call updates

- tools/license-checker/Cargo.toml
- tools/license-checker/src/fallback_syntax.yaml
- tools/license-checker/src/parser.rs
- tools/license-checker/testdata/number_signs.fallback
- tools/license-checker/testdata/plain_text
- tools/license-checker/testdata/shebang.fallback
- tools/license-checker/testdata/slashes.fallback
- tools/license-checker/testdata/source.unknown_file_type
The license checker uses the `syntect` crate to parse files wherever possible. `syntect` provides a number of syntax definitions for common language types. However, we have some files that `syntect` does not recognize. Currently, the license checker falls back to a hand-coded parser if it encounters a file type that `syntect` does not recognize. This PR removes that hand-coded parser, and replaces it with a fallback `syntect` syntax. This removes the duplicate parsing logic, replacing it with an easier-to-extend Sublime syntax definition file.
This will make it easier to resolve #3417, as one of the file types that `syntect` does not recognize does not support line comments (linker scripts), and parsing block comments is harder than parsing line comments.
> Use a fallback syntect syntax rather than a custom Rust parser in the license checker.

- .lcignore
- tools/license-checker/src/fallback_syntax.yaml
- tools/license-checker/src/parser.rs
- tools/license-checker/testdata/block_comments.ld
- tools/license-checker/testdata/block_comments.xml
As noted in #3417, there are two file types in the Tock repository that do not support line comments: XML, and linker scripts. This PR allows the license checker to operate on those files.
I will add license headers to XML files and linker scripts in a follow-up PR.
**Limitation**
This PR does not support the following comment format:
```rust
/* Licensed under ...
* SPDX-License-Identifier: ...
* Copyright ...
*/
```
because the license checker decodes the comment body as:
```
Licensed under ...
* SPDX-License-Identifier: ...
* Copyright ...
```
and errors on the leading `*`'s. I don't see an easy and reliable way to identify that comment style and filter out the leading `*`'s. Because block comments are rare in Tock's codebase, I don't feel that we should add complexity to handle them. …
> Add support for block comments to the license checker.

- kernel/src/platform/platform.rs
- Reorder the context switch callback getter to match the type def.
- Cleanup comments.
Minor fixes as I'm looking at (and writing about) this file.
n/a
n/a
> kernel: minor updates to platform.rs

- .lcignore
- boards/nordic/nrf52840_dongle/jtag/gdbinit_pca10040.jlink
- boards/nordic/nrf52840dk/jtag/gdbinit_pca10040.jlink
- boards/nordic/nrf52dk/jtag/flash-full.jlink
- boards/nordic/nrf52dk/jtag/flash-kernel.jlink
- boards/nordic/nrf52dk/jtag/gdbinit_pca10040.jlink
- tools/license-checker/src/fallback_syntax.yaml
- tools/license-checker/src/parser.rs
- tools/license-checker/testdata/number_signs.fallback
I tweaked the license checker's fallback parser so it accepts comments that start with `#` rather than `# `, which allows for a `#\n` line at the end of the header (as we allow for other file types).
> Add license headers to the `.jlink` files.

- tools/license-checker/src/main.rs
The license checker documentation gave two examples of block comment syntaxes that the license checker doesn't support; this adds an example of a syntax it *does* support.
> `licensecheck`: document a block comment style that works.

- .lcignore
- boards/imxrt1050-evkb/MIMXRT1052xxxxB.xml
- boards/imxrt1050-evkb/MIMXRT1052xxxxB_part.xml
AFAIK, these are the last files in the repository that should have license headers but don't, so this PR should resolve #3417.
> Add license headers to `*.xml` files.

- arch/rv32i/src/lib.rs
The current code is broken when linker relaxation of GP is enabled. The problem has not manifested yet because upstream LLD does not yet support relaxation of GP.
Plus, change the way `__global_pointer$` is referenced to `__global_pointer` plus a manual `$` in asm to properly use `link_name`. The current approach is confusing because there's no symbol named `__global_pointer`.
`make -C boards/opentitan/earlgrey-cw310 test` and manual assembly inspection
> Fix global pointer setup code

- boards/Makefile.common
By default, Rust does not enable `relax` target feature, and therefore no `R_RISCV_RELAX` will not be generated, causing no relaxation to be performed. This causes `auipc + jalr` far jump pair to be not optimised to near `jr` jump.
Taking earlgrey-cw310 as example, this change shaves a lot off the binary:
Size before this commit:
```
text    data     bss     dec     hex
141304      28   18976  160308   27234
```
Size after this commit:
```
text    data     bss     dec     hex
131272      28   18976  150276   24b04
```
This is 7% space saving in the .text!
`make -C boards/opentitan/earlgrey-cw310 test` and manual assembly inspection
> Ensure Rust code generated is eligible for linker relaxation

- kernel/src/utilities/static_ref.rs
- tools/svd2regs.py
This allows `Option<StaticRef<T>>` to be the same size as `StaticRef<T>`. There is no usage of null `StaticRef` right now and it would always be invalid: LLVM recognizes 0 as null and `.deref()` constructing a null reference is immediate UB. Just in case, this adds a check in svd2regs.py.
This also mentions the primary benefit of `StaticRef` (you can put one in a `const`) and improves safety documentation.
> Make StaticRef NonNull

- tools/license-checker/Cargo.toml
thiserror 1.0.37 depends on proc-macro2 `1.0`. Older versions of proc-macro2 do not compiler on newer nightly compilers. This dependency bump requires proc-macro2 1.0.63, which works on our current nightly toolchain.
> Update thiserror to 1.0.44.

- boards/nordic/nrf52840dk/src/main.rs
The commented code does not align with the code in the Tock Book tutorial and needs to be updated.
> Fix Commented HID Initialization Code

- boards/opentitan/src/pinmux_layout.rs
OpenTitan has a convention for which UARTs and I2C peripherals are mapped to which pins. This PR updates the pinmux layout to match that convention.
With this change, both the RX and TX pins of UART0 are mapped to the SAM3X chip on the cw310, allowing us to interact with the Tock console over USB without extra hardware.
This PR was tested by using tests in the OpenTitan project.
> opentitan: Rearrange UARTs and I2Cs.

- boards/nano_rp2040_connect/src/main.rs
- boards/pico_explorer_base/src/main.rs
- boards/raspberry_pi_pico/src/main.rs
A few of the board main files have `global_asm!` statements that are `#[cfg(...)]`-ed to disappear when built on non-embedded targets. This results in "unused import" warnings when `cargo check` and `cargo clippy` are run by `make prepush`.
Because writing `core::arch::global_asm` does not noticeably affect readability, I'm just removing the use statements rather than than adding `#[allow(unused_imports)]`.
> Resolve "unused import: `core::arch::global_asm`" warnings.

- libraries/tock-register-interface/src/macros.rs
Offsets and register file size could be defined as a constant expression like `(AUX_OFFSET + 0x20)`.
`test_fields!` macro will fail for such structs as offsets go directly to `concat!` macro which accepts only literals.
To avoid this failure, stringify the offset and size first.
Example:
```
const BAR_OFFSET: usize = 256;
register_structs! {
UartRegisters {
(0x00 => foo: ReadWrite<u32>),
(0x04 => _reserved),
((BAR_OFFSET) => bar: ReadWrite<u32>),
((BAR_OFFSET+0x04) => @END),
}
}
```
********************************************************************************
* Pre-Push checks all passed!                                                  
********************************************************************************
> test_fields!: stringify offset and size in error messages

- chips/lowrisc/src/uart.rs
This bug appears to have been previously fixed (#3641), then mistakenly un-fixed during a refactoring (#3729), probably due to merge skew. I'm reapplying the fix from #3641.
This PR was tested by running a UART test that I'm developing 100 times, and seeing no errors.
> [opentitan] Fix spurious `0` byte reads on the LowRISC UART driver.

- chips/earlgrey/src/epmp.rs
The existing ePMP code was developed and tested in environments that use a test ROM. On the real silicon, we instead use a ROM_EXT, which passes a different ePMP config to Tock than the test ROM. In particular, it:
1. Sometimes configures and locks entries 0 and 1 (depends on which ROM_EXT is in use).
2. Sets up several entries in a manner that works for Tock, but without the lock bit set.
3. Disables the Rule Lock Bypass bit (this breaks the dance the current constructor does with the MMIO region).
This ePMP config is documented at https://opentitan.org/book/sw/device/silicon_creator/rom_ext/doc/si_val.html#epmp.
This PR renames the existing EarlGreyEPMP constructor to `new_test_rom`, and introduces a new constructor for use with a ROM_EXT, called simply `new`. This constructor makes use …
> opentitan: Add ROM_EXT-compatible ePMP setup.

- arch/rv32i/src/pmp.rs
- boards/build.rs
Keep the error text contiguous in error messages so that they are easy to locate.
Fixes #4141 by making the dependency on unstable cargo for build explicit.
> fmt: make `panic!` error messages greppable

- boards/Makefile.common
On my mac, the sleep command does not accept a unit:
```
$ sleep 5s
usage: sleep seconds
```
So this just removes the 's' and makes the format match the other if block we have.
Should be straightforward
n/a
> boards: make: sleep on mac no units

- doc/reference/trd-appid.md
- doc/reference/trd104-syscalls.md
- doc/wg/core/README.md
I have moved on from Google and am currently at Better Bytes. This updates the core WG affiliation list as well as my email address in a couple of locations (as my @google.com email is no longer reachable).
> Update my affiliation.
