tock/tock

- Makefile
- src/apps/libs/firestorm.c
- src/apps/libs/firestorm.h
- src/chips/Makefile.mk
Minor fixes to platform independent files.
> Generic fixes

- src/process/lib.rs
Just one warning elimination. I am currently on rustc-7dce32e65 nightly
> Process lib - clone_from_slice stable

- src/chips/nrf51822/Makefile.mk
- src/chips/sam4l/Makefile.mk
- src/chips/sam4l/lib.rs
- src/main/Makefile.mk
@alevy Should be an easy merge, but just wanted to call your attention to it in case I did anything silly. 
It took me longer than I care to admit, but I think I have a pretty decent handle on the rust inline assembly syntax, including reading and writing arbitrary rust variables from assembly, if we find that we need that down the line for anything.
> Hard fault handler

- .travis.yml
- Common.mk
- README.md
- src/chips/nrf51822/Makefile.mk
- src/chips/sam4l/Makefile.mk
- src/chips/sam4l/lib.rs
- src/chips/sam4l/target.json
- src/common/ring_buffer.rs
- src/drivers/console.rs
- src/drivers/isl29035.rs
- src/drivers/lib.rs
- src/drivers/nrf51822_serialization.rs
- src/drivers/timer.rs
- src/platform/storm/lib.rs
- src/process/container.rs
- src/process/lib.rs
- src/process/mem.rs
- src/process/process.rs
- src/support/arm.rs
- tools/elf2tbf/src/main.rs
I have not actually tested this on hardware. But hey, it compiles, that means it must work, right? :)
Unfortunately I had to disable debugging info because of a rustc bug: rust-lang/rust#25270. We can either live with this for now, or hold on merging this until the bug is fixed.
> Upgrade to newest Rust nightly

- boards/storm/README.md
Just tried to go through this process on ubuntu and finding the right packages for libftdi was a bit of a 
headache. Updated the readme to reflect the solution.
> Updated the readme to be more ubuntu friendly

- Makefile
- README.md
- tools/run_cargo_fmt.sh
Quick addition to readme to explain what you need to do.
> Add `make fmt`

- boards/storm/src/io.rs
Differentiates it from the blink app.
> Update storm panic! to blink interesting pattern

- boards/nrf51dk/src/main.rs
- chips/nrf51/src/rtc.rs
- kernel/src/hil/alarm.rs
Previously, it was using a high frequency clock. This switches it over to use the lower power RTC.
> Switched the TimerAlarms to use the RTC on the nrf51dk

- chips/sam4l/src/ast.rs
- chips/sam4l/src/bpm.rs
- chips/sam4l/src/gpio.rs
- chips/sam4l/src/nvic.rs
- chips/sam4l/src/scif.rs
Chose files that I don't think conflict with outstanding pull requests.
> Update some of SAM4L to VolatileCell

- userland/examples/ble-serialization/main.c
- userland/examples/c_hello/main.c
- userland/examples/gpio_test/main.c
- userland/examples/rf233/rf233.c
- userland/examples/security_app/main.c
- userland/examples/sensors/main.c
- userland/examples/spi_buf/main.c
- userland/examples/spi_byte/main.c
- userland/examples/tmp006/main.c
- userland/libtock/Makefile
- userland/libtock/console.c
- userland/libtock/console.h
- userland/libtock/crt1.c
- userland/libtock/firestorm.h
- userland/libtock/gpio.c
- userland/libtock/gpio.h
- userland/libtock/isl29035.c
- userland/libtock/isl29035.h
- userland/libtock/nrf51_serialization.c
- userland/libtock/nrf51_serialization.h
- userland/libtock/spi.c
- userland/libtock/spi.h
- userland/libtock/sys.c
- userland/libtock/timer.c
- userland/libtock/timer.h
- userland/libtock/tmp006.c
- userland/libtock/tmp006.h
- userland/libtock/tock.c
- userland/libtock/tock.h
Closes #143
* Move firestorm functionality into separate libs (spi/nrf51/timer)
* Fixup example apps
* Fixed a few lint issues
> Refactor userlib

- .travis.yml
- userland/Makefile
- userland/examples/ble-serialization/Makefile
- userland/examples/blink/Makefile
- userland/examples/blink_sync/Makefile
- userland/examples/build_all.sh
- userland/examples/c_gpio/Makefile
- userland/examples/c_hello/Makefile
- userland/examples/gpio_test/Makefile
- userland/examples/rf233/Makefile
- userland/examples/security_app/Makefile
- userland/examples/sensors/Makefile
- userland/examples/spi_buf/Makefile
- userland/examples/spi_byte/Makefile
- userland/examples/tmp006/Makefile
- userland/libtock/Makefile
Not yet tested on any HW (will do tomorrow), but all apps build correctly.
@bradjc this should just about earn that damn cookie.
> Userland make fixes

- arch/cortex-m4/src/lib.rs
- arch/cortex-m4/src/scb.rs
Allows for software to reset itself.
> SAM4L: Add SCB module + reset

- capsules/src/timer.rs
- userland/libtock/timer.c
- userland/libtock/timer.h
Expose the current timer value to applications.
> Timer: Add read timer value function

- boards/imix/src/main.rs
- boards/storm/src/main.rs
Makes main.rs a little less daunting, and easier to parse.
> Storm+Imix: Shrink pin configurations

- chips/sam4l/src/usart.rs
This is a start on adding SPI support to the USART module. `read_write_bytes()` seems to work, the byte level ones may not, but I'm not enthusiastic about supporting those anyway.
> Add SPI to USART in SAM4L

- capsules/src/lib.rs
- capsules/src/tsl2561.rs
- userland/examples/tests/tsl2561/Makefile
- userland/examples/tests/tsl2561/main.c
- userland/libtock/tsl2561.c
- userland/libtock/tsl2561.h
Another sensor on the BLEES board.
> Add TSL2561 Light Sensor capsule

- kernel/src/common/result.rs
These allow operations to signify whether they were performed successfully or a run-time error occurred. As we move towards standardizing APIs and error condition handling, these will be needed.
> Standard return value codes. 

- boards/imix/src/i2c_dummy.rs
- boards/imix/src/main.rs
- boards/imix/src/spi_dummy.rs
- kernel/src/hil/i2c.rs
Ports i2c_dummy to imix with some minor tweaks
> Port I2C tests to imix

- doc/tutorials/01_running_blink.md
So I'm not sure if this should go in a different folder, and if so I can move it.
> Doc: Add first tutorial

- chips/sam4l/src/pm.rs
Allow board files to select using the PLL as a 3x multiplier for OSC0.
Tested on some of the signpost hardware.
> SAM4L: Add PLL as clock source

- boards/imix/src/main.rs
- boards/storm/src/main.rs
- capsules/src/isl29035.rs
Based on the ADC resolution, there is an integration time between when
a measurement is started and when the result is ready. This adds a timer
to wait for that amount of time.
I believe this isn't an issue with I2C at 100 kHz, as the latency of
writing bytes over I2C was long enough that the 410 us waiting period
was met. With faster I2C speeds, however, this is necessary. It will
also be necessary if a 12 bit or 16 bit conversion is used in the
future.
Fixes #165
> ISL29035: Add timer to wait for integration

- vagrant/.gitignore
- vagrant/README.md
- vagrant/Vagrantfile
The current version will let you build Tock, but it doesn't set up
serial ports / any other way to flash from inside the VM
Towards #109.
> Add Tock Vagrant image

- doc/tutorials/04_sensors_and_drivers.md
- doc/tutorials/README.md
Covers using syscalls and `yield()`.
> Add tutorial #4

- kernel/src/hil/flash.rs
- kernel/src/hil/mod.rs
There is room to expand the interface in the future, but it seems worth checking in as simple an interface as possible for starters.
> Add simple read/write interface to flash.

- userland/Makefile
> userland: set default PKG_NAME

- .travis.yml
- Makefile
- tools/list_boards.sh
Update travis to use this so that it will automatically pick up
new targets.
> Add `make allboards` target to root

- kernel/src/ipc.rs
- kernel/src/process.rs
- userland/Makefile
- userland/libtock/sys.c
A collection of small changes accrued while working on other stuff
> Little nits

- doc/Userland.md
- kernel/src/process.rs
pulling these out of the LTO patch series that'll take a while to merge and my git stash history
> Small debug stuff

- boards/hail/src/main.rs
- boards/storm/src/main.rs
- capsules/src/lib.rs
- capsules/src/rng.rs
- doc/Syscalls.md
- userland/examples/tests/rng/Makefile
- userland/examples/tests/rng/main.c
- userland/libtock/rng.c
- userland/libtock/rng.h
Added RNG capsule and user C interface.
> Userland RNG

- Makefile.common
- boards/hail/Makefile
- boards/imix/Makefile
- boards/nrf51dk/Makefile
- boards/storm/Makefile
Like the others before, ripping out a bunch of copied stuff into a common file. Motivated by trying to add `cargo --verbose` support and realizing that I'd have to add it to 4 files otherwise.
> Make updates

- userland/Makefile
I'll add this to tockloader too in a sec
> Validate that all required gcc switches were used

- chips/sam4l/src/i2c.rs
When doing a write_read(), if handling the transition between the two gets delayed and only one byte is to be read, using DMA no longer works since the byte is already in the RHR register. This checks for this specific case and handles it correctly.
Tested by running hail and accel_leds simultaneously.
> SAM4L I2C: Handle short read_write() correctly

- chips/sam4l/src/i2c.rs
This file has always been involved in pull requests and had not been updated to volatile cell yet.
> sam4l: i2c: update TWIM to VolatileCell

- chips/sam4l/src/usart.rs
* Make the ChipSelect an Option<GPIO>>, allowing drivers to use the RTS line if desired
* Make the SPI transaction end on DMA RX complete, when applicable
The second bullet goes part-way to fixing issue #274. In the case of a
SPI transaction that does a read, the CS line will now be deasserted
properly. In the case of a many-byte write with no read, the problem is
not solved (but has not been made worse either).
This has been tested and works on the signpost platform which uses FRAM
over SPI over USART including both read/writes and write-only transfers.
> Two small updates to SPI over USART

- boards/imix/README.md
- doc/Getting_Started.md
This is mostly a clone of the storm README, with irrelevant things
removed and some parts left as TODOs.
I'll be updating this as I learn more.
> boards/imix: add README on flashing software

- kernel/src/process.rs
This should give a more realistic view of how much stack is being used.
It's still not necessarily the most stack that has ever been used, only the most that was ever in use when a syscall happened, but still better than what we were doing before. The current value of the stack pointer is still printed among the registers.
This is a small change and I'm going to pull it once Travis passes. PR'd mostly just so people can be aware that it happened.
> Keep track of minimum stack pointer

- boards/imix/src/main.rs
- capsules/src/radio.rs
- capsules/src/rf233.rs
- doc/reference/trd-radio.md
- kernel/src/hil/radio.rs
Add support for 64-bit source and destination addresses. Also add the RadioCrypto trait to kernel::hil::radio.
> Rf233 addrs

- chips/sam4l/src/ast.rs
We've been seeing issues using the AST when setting an alarm to very
short (a few tics) future clock values.
The datasheet has the following ominous language (Section 19.5.3.2):
> Because of synchronization, the transfer of the alarm value will not
> happen immediately. When changing/setting the alarm value, the user must
> make sure that the counter will not count the selected alarm value before
> the value is transferred to the register. In that case, the first alarm
> interrupt after the change will not be triggered.
In practice, we've observed that when the alarm is set for a counter value
less than or equal to four tics ahead of the current counter value, the
alarm interrupt doesn't fire.
This commit simply rounds up to at least eight tics, which seems safe
enough and in practice has …
> Fix SAM4L AST bug when delay is very short

- chips/sam4l/src/lib.rs
Basically decode the CFSR and HFSR registers on kernel faults.
> sam4l: print more state on kernel fault

- doc/Compilation.md
- doc/Memory_Layout.md
- doc/Overview.md
- doc/Userland.md
- userland/tools/elf2tbf/README.md
Also add some IPC documentation.
> doc: update memory map and other doc

- kernel/src/ipc.rs
Ugh the diff is really ugly, but all I did was add comments. Then I had to run rustfmt, which apparently decided the format should be different now that it has comments.
> IPC: add comments to IPC

- capsules/src/console.rs
- capsules/src/ltc294x.rs
- capsules/src/ninedof.rs
- capsules/src/rf233.rs
- capsules/src/rng.rs
- kernel/src/hil/ninedof.rs
`ERESERVE` in Tock means "You needed to do something else first. Likely you need to call `allow` or `subscribe`".
> capsules: update return codes to be more specific

- doc/Syscalls.md
We really really really really really really really really need to be more careful about this before merging pull requests.
> doc: sync syscalls with the source

- doc/tutorials/05_ipc.md
- doc/tutorials/README.md
- userland/examples/tutorials/05_ipc/README.md
- userland/examples/tutorials/05_ipc/led/Makefile
- userland/examples/tutorials/05_ipc/led/main.c
- userland/examples/tutorials/05_ipc/logic/Makefile
- userland/examples/tutorials/05_ipc/logic/main.c
- userland/examples/tutorials/05_ipc/rng/Makefile
- userland/examples/tutorials/05_ipc/rng/main.c
I made up an example app that uses two services to blink some LEDs.
> tutorials: add #5: IPC

- arch/cortex-m4/src/mpu.rs
To find subregion sizes that align with the base address, we were
simply doing `start % len`. This only results in a power-of-two
subregion size when `start` only has 1`s in bits more significant
than than those in `len` (intuitively, when the non-power-of-two bits in
`start` are divisible by `len`).
Instead, we find the largest power-of-two that `start` is aligned to
(divisible by), by simply finding the lowest 1-bit in `start` and using
it as the highest (and only) bit in the subregion size. The function
later validates that this is otherwise a valid subregion (>= 32 and
results in a valid region size).
> Fixs MPU bug that creates non-power-of-two regions

- chips/sam4l/src/pm.rs
(I *think* I've got this right.)
> sam4l pm: fix some comments about clock sources

- tools/run_cargo_fmt.sh
- userland/tools/uncrustify/uncrustify.sh
> tools: check for unstaged changes before formatting

- boards/imix/src/main.rs
- capsules/src/crc.rs
- capsules/src/ltc294x.rs
- capsules/src/mcp23008.rs
Making progress towards using the updated `static_init!` API.
> static_init! cleanup

- capsules/README.md
Add organized list of capsules so people can see what Tock supports in a more organized fashion.
> capsules: doc: update readmes

- boards/hail/src/main.rs
- capsules/README.md
- capsules/src/dac.rs
- capsules/src/lib.rs
- chips/sam4l/src/chip.rs
- chips/sam4l/src/dac.rs
- chips/sam4l/src/lib.rs
- doc/Syscalls.md
- kernel/src/hil/dac.rs
- kernel/src/hil/mod.rs
- userland/examples/tests/dac/Makefile
- userland/examples/tests/dac/README.md
- userland/examples/tests/dac/main.c
- userland/libtock/dac.c
- userland/libtock/dac.h
- Pretty basic DAC support.
- Userland test app.
> SAM4L: Add DAC driver

- .travis.yml
- boards/Makefile.common
- boards/nrf51dk/src/main.rs
- doc/Getting_Started.md
- vagrant/Vagrantfile
I was just super wrong. I just didn't upgrade to the right Rust
version...
@niklasad1 can you approve when you're satisfied that it actually works this time?
> Remove inline(never) upgrade Rust version

- kernel/src/debug.rs
Pulled this from Phil's flash branch.
> debug.rs: Make length a const variable.

- chips/sam4l/src/scif.rs
> sam4l: fix DFLL name

- chips/sam4l/src/crccu.rs
- chips/sam4l/src/lib.rs
> sam4l: rename crccu interrupt

- userland/examples/build_all.sh
Borrowing this from signpost, the idea is to defer the error until all
apps have tried to build, so that you get a complete list of things you
need to fix when Travis fails rather than going in a loop.
> travis: defer userland app failure to get whole list

- tools/run_cargo_fmt.sh
> tools: verify rustfmt version before running

- chips/sam4l/src/helpers.rs
I think this is ok and useful?
> sam4l: remove unused functions in helpers.rs

- userland/libtock/tock.c
- userland/libtock/tock.h
Mirrors `strerror` from regular errno
> Add human-friendly error code explanations

- userland/examples/ble-uart/Makefile
- userland/examples/ble-uart/README.md
- userland/examples/ble-uart/ble_nus.c
- userland/examples/ble-uart/ble_nus.h
- userland/examples/ble-uart/main.c
This is an app that demonstrates how to setup a serial over BLE connection.
Tested with hail and an android tablet.
> userland: add ble-uart app

- boards/hail/src/main.rs
- boards/nrf51dk/src/main.rs
- capsules/src/symmetric_encryption.rs
- chips/nrf51/src/aes.rs
- chips/sam4l/src/aes.rs
- chips/sam4l/src/chip.rs
- chips/sam4l/src/lib.rs
- kernel/src/hil/symmetric_encryption.rs
- userland/examples/tests/aes/main.c
- Remove some duplication from symmetric encryption capsules.
- Make the symmetric encryption HIL more like other HIL interfaces.
- Add AES driver for SAM4L that conforms to the HIL interface.
- Add symmetric encryption driver to Hail.
- Fix a couple typos.
> AES improvements and SAM4L AES driver

- userland/AppMakefile.mk
- userland/Helpers.mk
- userland/TockLibrary.mk
- userland/examples/format_all.sh
- userland/tools/check_unstaged.sh
- userland/tools/uncrustify/uncrustify.sh
A bit copy/pasty, but that's fine for a one-off like this IMO
Resolves Problem 1 from #432.
> style: only check for unstaged changes once

- chips/sam4l/src/spi.rs
@ptcrews @phil-levis @bradjc
- real_rate: We corrected the check for whether the division was exact
from `clock % rate` to `clock % real_rate`, but that introduced a new
bug, because then it actually tries to increment it when it is already
at the slowest rate (which ends up setting scbr to the invalid 0). The
solution is to only get a slower baud rate if we are not at the slowest
rate already.
- transfers_in_progress: the hunk that set this to 0 was accidentally
deleted when we squashed/reordered some commits so that our code
introduces SPI slave and then reverts the board initialization code.
> Fixes two bugs in the SPI code introduced in 7217345d

- userland/AppMakefile.mk
> tools: use = rather than == for string equality in sh

- boards/nrf52dk/README.md
- boards/nrf52dk/jtag/jdbserver_pca10040.sh
> nRF52 fixed typos/consistency

- userland/TockLibrary.mk
- userland/libtock/alarm_timer.c
- userland/libtock/ltc294x.c
I grep'd for all use of `==` in makefiles, these are the only ones left I could find
Will merge as soon as travis passes
> More sh bash equal problems

- arch/cortex-m4/src/mpu.rs
- kernel/src/platform/mpu.rs
Also update comments for the `enable()` function.
> mpu: add disable() function

- userland/AppMakefile.mk
This is the complementary half of 2db20bb3b, providing the `make`
rules to actually generate the requested listings.
Verified by checking that `crash_dummy`'s PC is a null pointer ldr
> Automatic relocation-aware listing generation

- doc/Compilation.md
- doc/Memory_Layout.md
- doc/Mutable_References.md
- doc/README.md
- doc/Startup.md
- doc/Syscalls.md
- doc/Userland.md
Generally make docs more consistent and update to latest code.
> doc: improve main tock docs

- kernel/src/container.rs
This introduces another smart-pointer type, Borrowed, for the case where the
memory is not actually owned but borrowed. I would have preferred to just use
`&mut T`, but capsules are relying on the value including an `app_id`, so this
seemed like the smallest delta.
Fixes #538.
> container: stop using Owned with enter, each

- boards/nrf52dk/src/main.rs
nRF52 remove unused chip initialization
> nRF52 remove unused chip initialization

- boards/hail/src/main.rs
Just making things a little more consistent.
> hail: don't special case some `use` statements

- boards/hail/src/main.rs
- kernel/src/platform/mod.rs
A quick PR before the ✈️ lands
> Add some more comments to hail platform

- CONTRIBUTING.md
Should address the other part of Jay's issue from a little while ago
> doc: add style section to contributing

- boards/nrf51dk/README.md
- boards/nrf52dk/README.md
- doc/Getting_Started.md
- doc/tutorials/01_running_blink.md
- doc/tutorials/02_button_print.md
- doc/tutorials/03_ble_scan.md
- doc/tutorials/04_sensors_and_drivers.md
- doc/tutorials/05_ipc.md
- doc/tutorials/README.md
Hi,
This PR tries to improve the following:
- Clarify in the documentation about the two programming methods ```program vs flash```
- Changed the tutorials a little bit and added a paragraph which boards are supported
- Added additional method for programming for nRF5X since tockloader still don't work for me personally!
- Close [#574](https://github.com/helena-project/tock/issues/574)
Thoughts?
> [getting started docs and tutorials]

- boards/imix/src/main.rs
- doc/courses/sosp/README.md
- doc/courses/sosp/application.md
- userland/examples/solutions/sosp-ble-ess.c
- userland/examples/solutions/sosp-repeat-hello.c
- userland/examples/solutions/sosp-sensors.c
- userland/examples/sosp/Makefile
- userland/examples/sosp/main.c
This is partway done; it gets through the hello world, timer, and sensor stuff.
I'm still working on the remainder: LEDs, BLE
> sosp userland application: translate to C

- kernel/src/process.rs
Before we were trusting the app to request a reasonable amount of ram in
its header, and using that ram to set up pointers and other per-app
kernel-level state. However, if an app requests 0 ram we were still
setting up this state (causing a buffer overflow) and then panicing in
the MPU because we were trying to setup an MPU region with zero length.
This changes the app ram handling to ensure that the app gets at least
enough ram to setup the kernel state.
Apps can request 0 now, and they will likely still crash but it will be
an app fault and not a kernel fault.
This pull request was tested by running some apps on hail.
> Always set process RAM to minimum length

- chips/nrf51/Cargo.lock
- chips/nrf51/src/clock.rs
- chips/nrf51/src/i2c.rs
- chips/nrf51/src/radio.rs
- chips/nrf51/src/uart.rs
> nrf51: use staticref

- chips/tm4c129x/Cargo.lock
- chips/tm4c129x/src/gpio.rs
- chips/tm4c129x/src/gpt.rs
- chips/tm4c129x/src/sysctl.rs
- chips/tm4c129x/src/uart.rs
> ek: convert to staticref

- chips/cc26xx/Cargo.lock
- chips/cc26xx/src/aon.rs
- chips/cc26xx/src/gpio.rs
- chips/cc26xx/src/ioc.rs
- chips/cc26xx/src/prcm.rs
- chips/cc26xx/src/rtc.rs
- chips/cc26xx/src/trng.rs
- chips/cc26xx/src/uart.rs
> cc26xx: use staticref

- chips/nrf52/src/adc.rs
- chips/nrf52/src/lib.rs
First pass which only supports single samples.
Blocked on ADC HIL changes.
This pull request was tested by reading sensor on ACD52832.
n/a
> nrf52: add adc driver

- arch/cortex-m/src/syscall.rs
This is currently causing apps to crash, so this is a quick fix.
Making an issue so that there is a record. This is a temporary fix.
> kernel: revert default action when app is changed

- kernel/src/introspection.rs
If the process is not valid, to help with debugging.
n/a
> introspection: return "unknown", not empty name

- tools/svd2regs.nix
Nix environment for working with `svd2regs.py`
> tools: Add `svd2regs.nix`

- .gitignore
Add `.gdb_history` to `.gitignore`
> .gitignore: Add `.gdb_history`

- doc/Design.md
Amit is the original author. I just extracted this information out from PR
#1457, discussion, as I think it is useful for potential Tock contributors to
know about this early.
> doc/Design.md: Add 'Some in-kernel design principles` section

- kernel/src/grant.rs
This fixes two issues:
1. Due to automatic type inference, grant regions were getting allocated to make `*mut u8` the correct pointer return type, which means all grant regions were being allocated as 1 byte.
This has been fixed in two ways: we explicitly use `T::default()` instead of `Default::default()`, so we allocate something of size `sizeof(T)` and not whatever the return type matches. This also changes the return type to be `*mut T`.
2. There was an extra de-reference of the grant pointer, so we were storing not the grant pointer to the actual grant region, but instead whatever the first bytes of the grant region were as the pointer.
This has been fixed by removing a `*`.
I also updated the variable names to better match what they actually are, and added more comments in case …
> kernel: grant: fix allocation

- boards/opentitan/src/main.rs
Due to an OpenTitan hardware bug (see https://github.com/lowRISC/opentitan/issues/2598)
USB doesn't work. Let's just disable USB by default to avoid confusing
people.
Replaces #2115
travis
n/a
> opentitan: Disable USB support by default

- capsules/src/si7021.rs
This PR fixes a Rule 2 (Never use more than one state variable) violation.
The si7021 capsule cannot use the presence of a buffer as a signal that the driver is free since the buffer is free when the sensor is waiting for the measurement to finish.
This pull request was tested by running sensors and hail on hail.
n/a
> capsules: si7021: only use state for state var

- kernel/src/sched.rs
> Fix grammar

- arch/rv32i/src/syscall.rs
The crate structure and name has changed over time, this updates to a more consistent name.
Backported from 2.0 branch.
travis
n/a
> arch: rv32i: rename stored state

- doc/wg/core/notes/core-notes-2021-05-21.md
[Rendered](https://github.com/jrvanwhy/tock/blob/core-notes-2021-05-21/doc/wg/core/notes/core-notes-2021-05-21.md)
> Add core WG notes for 2021-05-21.

- doc/wg/core/notes/core-notes-2021-05-28.md
[Rendered](https://github.com/tock/tock/blob/corenotes/2021-05-28/doc/wg/core/notes/core-notes-2021-05-28.md)
> Add core WG notes for 2021-05-28

- doc/wg/core/notes/core-notes-2021-07-02.md
[Rendered](https://github.com/jrvanwhy/tock/blob/core-notes-2021-07-02/doc/wg/core/notes/core-notes-2021-07-02.md)
These meeting notes are from 9 days ago, not last Friday (sorry for the delay).
> Add core WG notes from 2021-07-02

- kernel/src/debug.rs
Remove `begin` prefix from `begin_debug_fmt` and `begin_debug_verbose_fmt` since there does not appear to be a finish or end that should accompany it.
Also add a non-newline version of this function.
This does not need to make it in by Tock 2.0 release
- None
> debug: rename begin_debug_fmt and add non-newline version

- doc/wg/core/notes/core-notes-2022-02-18.md
[Rendered](https://github.com/jrvanwhy/tock/blob/core-notes-2022-02-18/doc/wg/core/notes/core-notes-2022-02-18.md)
> Add core WG meeting notes for `2022-02-18`.

- doc/wg/core/notes/core-notes-2022-03-04.md
[Rendered](https://github.com/jrvanwhy/tock/blob/core-notes-2022-03-04/doc/wg/core/notes/core-notes-2022-03-04.md)
> Add core WG notes for 2022-03-04.

- doc/wg/core/notes/core-notes-2022-03-18.md
[Rendered](https://github.com/jrvanwhy/tock/blob/core-notes-2022-03-18/doc/wg/core/notes/core-notes-2022-03-18.md)
> Core WG notes for 2022-03-18.

- doc/wg/core/notes/core-notes-2022-04-08.md
[Rendered](https://github.com/jrvanwhy/tock/blob/core-notes-2022-04-08/doc/wg/core/notes/core-notes-2022-04-08.md)
> Add core WG notes for 2022-04-08.

- doc/wg/core/notes/core-notes-2022-06-03.md
[Rendered](https://github.com/jrvanwhy/tock/blob/core-notes-2022-06-03/doc/wg/core/notes/core-notes-2022-06-03.md)
> Add core WG notes for 2022-06-03

- boards/clue_nrf52840/README.md
- boards/pico_explorer_base/README.md
- doc/reference/trd-digest.md
- doc/reference/trd-uart.md
Used the ./tools/check-links.sh tool.
n/a
n/a
> readmes: update links

- doc/wg/core/notes/core-notes-2022-07-29.md
[Rendered](https://github.com/jrvanwhy/tock/blob/core-notes-2022-07-29/doc/wg/core/notes/core-notes-2022-07-29.md)
> Add core notes for 2022-07-29

- doc/wg/core/notes/core-notes-2022-09-30.md
[Rendered](https://github.com/jrvanwhy/tock/blob/core-notes-2022-09-30/doc/wg/core/notes/core-notes-2022-09-30.md)
> Add core WG notes for `2022-09-30`.

- doc/wg/core/notes/core-notes-2022-10-07.md
[Rendered](https://github.com/jrvanwhy/tock/blob/core-notes-2022-10-07/doc/wg/core/notes/core-notes-2022-10-07.md)
> Add core WG notes for 2022-10-07

- doc/wg/core/notes/core-notes-2022-11-11.md
[Rendered](https://github.com/jrvanwhy/tock/blob/core-notes-2022-1-1/doc/wg/core/notes/core-notes-2022-11-11.md)
> Add core WG notes for `2022-11-11`.

- doc/wg/core/notes/core-notes-2022-12-16.md
[Rendered](https://github.com/jrvanwhy/tock/blob/core-notes-2022-12-16/doc/wg/core/notes/core-notes-2022-12-16.md)
> Add core WG notes for 2022-12-16.

- tools/license-checker/src/main.rs
- tools/license-checker/src/parser.rs
This PR should not be merged until after #3449 is merged, as it documents some capabilities that PR adds.
Closes #3419
> Improve the license checker's documentation.

- doc/wg/core/notes/core-notes-2023-06-16.md
[Rendered](https://github.com/jrvanwhy/tock/blob/core-notes-2023-06-16/doc/wg/core/notes/core-notes-2023-06-16.md)
> Core WG notes for `2023-06-16`.

- doc/wg/core/notes/core-notes-2023-09-08.md
[Rendered](https://github.com/jrvanwhy/tock/blob/core-notes-2023-09-08/doc/wg/core/notes/core-notes-2023-09-08.md)
> Add core WG notes for 2023-09-08

- doc/wg/core/notes/core-notes-2023-11-03.md
[Rendered](https://github.com/jrvanwhy/tock/blob/core-notes-2023-11-03/doc/wg/core/notes/core-notes-2023-11-03.md)
> Add core WG notes for 2023-11-03

- kernel/src/kernel.rs
See issue #3738 for more information, but in short: the no-wait flag should only be written in yield-no-wait, not yield-wait.
It may be easier to review this by looking at the [new version](https://github.com/jrvanwhy/tock/blob/dont-corrupt-memory/kernel/src/kernel.rs#L812) rather than looking at the diff.
This pull request was tested by using a work-in-progress test app in OpenTitan.
> Only write the no-wait flag in yield-no-wait.

- doc/wg/core/notes/core-notes-2024-03-08.md
[Rendered](https://github.com/jrvanwhy/tock/blob/core-notes-2024-03-08/doc/wg/core/notes/core-notes-2024-03-08.md)
> Core WG notes for 2024-03-08

- capsules/system/src/process_checker/basic.rs
Can just use .into().
travis
n/a
> capsules: appid: names: simplify implementation

- doc/wg/core/notes/core-notes-2024-09-20.md
[Rendered](https://github.com/jrvanwhy/tock/blob/core-notes-2024-09-20/doc/wg/core/notes/core-notes-2024-09-20.md)
> Core WG notes for 2024-09-20.
